### ISSUE TITLE
Updateprozedere im setup.sh

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#102]
Hallo rix1337,

Zurst mal danke für dieses tolle Tool, funktioniert wir am Schnürchen.
Verwende es auf einer Synology und scrape damit SJ Serien.

Nun zur eigentlichen Frage:
Lässt es sich evtl. machen in dein setup.sh ein Updateprozedere einzubauen, dh. wenn RSScrawler schon installiert ist, das so Dinge wie Einstellungen, Datenbanken und Textfiles (Regex.txt etc.) erhalten bleiben?

Wenn ich aktuell das Script ausführe wird alles auf neu zurückgesetzt :(

Danke & Grüße
DKeppi

**Comment by rix1337** [comment]
Kommt im nächsten Update.

Ansonsten kannst du jederzeit per `cd` in den RSScrawler Ordner wechseln und dann per
```
git fetch --all
git reset --hard origin/master
git pull origin master
```

updaten. Dabei bleiben die Einstellungen, etc. erhalten.

**Comment by DKeppi** [comment]
Perfekt!

Vielen Dank für die Info, dann mach ich das Update so - super! :)
