### ISSUE TITLE
Verbesserungsvorschläge - crawljob Einstellungen

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#103]
Hi rix1337,

hätte da ein paar Ideen die mir das Leben mit deinem Plugin etwas erleichtern würden, besonders nach einem Update.

Ich passen manuell in der common.py immer die Werte zum Downloadfolder (will keinen Unterordner RSScrawler) und auch zu den erstellten crawljobs (kein autom. Download, kein autom. Start etc.) an.

Viell. könnte man das alles im Webserver integrieren (zB. Checkbox für die TRUE/FALSE Werte und Feld für Downloadpfad)?

Sind wie gesagt nur Ideen, aber das würde den Crawler noch perfekter machen :)

Grüße
DKeppi

**Comment by rix1337** [comment]
Hi,

danke für die Rückmeldung!

Den Unterordner werde ich beibehalten.
Autostart true/false kommt aber auf die Updateliste.

Gruß

**Comment by DKeppi** [comment]
Hi

Toll das du etwas davon umsetzen willst...

Gruß
DKeppi

**Comment by rix1337** [comment]
Updaten & neustarten.

Danach kannst du (ausschließlich über die RSScrawler.ini) sowohl den Autostart, als auch das Unterverzeichnis deaktivieren.

Setz dazu einfach unter [Crawljob] die neuen Optionen autostart und subdir auf False.

**Comment by DKeppi** [comment]
Vielen Dank :)

**Comment by rix1337** [comment]
Gerne 😄

**Comment by rix1337** [comment]
Sagt ruhig Bescheid wie der crawler so läuft. Sowas kleines lässt sich leicht beheben!

**Comment by DKeppi** [comment]
Nach Eintrag von
```
[Crawljobs]
autostart = False
subdir = False
```
in der RSScrawler.ini hats geklappt :)


Blöderweise ist in den Crawljobs AUTOCONFIRM = TRUE, daher werden die Downloads wieder gestartet :(

**Comment by rix1337** [comment]
Das war mir nicht klar. Sollte gefixt sein.

**Comment by DKeppi** [comment]
Dankeschön :)
