### ISSUE TITLE
Webinterface mit Login absichern

### ISSUE THREAD

**Issue by postboy99** [rix1337/RSScrawler#127]
Hallo,

erst einmal danke für dieses tolle Tool!
Ist es möglich das Webinterface mit einem Login zu versehen/abzusichern?
Da ich das Webinterface auch von außen erreichbar gemacht habe, bekomme ich dauern Einträge von fremden Leuten, dass ich das Webinterface mit Passwort versehen soll.

Vielen Dank

**Comment by rix1337** [comment]
Hi, 

Dafür reicht ein einfacher Webserver wie nginx mit entsprechendem Reverse Proxy. Ich würde dringend davon abraten RSScrawler selbst ans Internet zu lassen.

Falls sich der Login direkt in Cherrypy einbauen lässt reiche ich das gerne nach..

..bis dahin nimm unbedingt deine Portfreigabe raus!

Es gibt sehr gute Docker Container die dir die komplette Einrichtung abnehmen, inklusive kostenlosem HTTPS.

Bspw. https://github.com/linuxserver/docker-letsencrypt

Ohne Https ist ein Passwort auch nicht wirklich sicher..

**Comment by postboy99** [comment]
Danke für die schnelle Antwort.
Da ich schon stolz war, dass ich RSScrawler zum laufen bekommen zu haben, ist mir das mit den Docker Container glaube etwas zu viel.
Ich werde die Portfreigabe rausnehmen, fand es nur schön bequem, von unterwegs Zugriff darauf zu haben.

Danke dir soweit.

**Comment by rix1337** [comment]
Kein Thema, hatte da nie richtig drüber nachgedacht.

Wichtig ist nur, dass eigentlich nur die Absicherung hinter einem Webserver tatsächlich sicher sein wird.. Ein einfaches Passwort wird sich trotzdem irgendwie einbauen lassen!

**Comment by postboy99** [comment]
Das wäre toll.
Man muss sich dann nur im Klaren sein, dass es ohne https auch dann nicht wirklich sicher ist.

PS: Muss ich den Thread jetzt schließen?

**Comment by rix1337** [comment]
Ich sehe erstmal, was sich machen lässt.

Entweder schließe ich nach erfolgter Anpassung, oder weil sich der Aufwand nicht lohnt 😃

**Comment by rix1337** [comment]
Wenn du die Gelegenheit hast dir einen Server mit HTTPs einzurichten, nimm noch Fail2Ban dazu und das ganze ist deutlich sicherer!
https://www.youtube.com/watch?v=8r8WlMqR5aY

**Comment by rix1337** [comment]
Die Implementierung über den cherrypy-Server wäre zu aufwändig und nicht sicher, ohne https.

Ich empfehle dringend eine ordentliche reverse proxy mit letsencrypt-Zertifikat, fail2ban und HTTPauth zu verwenden.

Orientierungshilfe bspw. hier: https://github.com/rix1337/docker-organizr
