### ISSUE TITLE
Fehlverhalten beim Speichern der Einstellungen

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#131]
Habe einen Fehler in der aktuellen Version 3.0.9 entdeckt!

Speicher ich die Suchlisten mit dem oberen Speichern Button, wird normal neugestartet und alles ist gut!
Speichere ich aber mittels unterem Speichern Button (der nach Unterordner nutzen aktiviert/deaktiviert), dann wird der pushbullet Token entfernt und die Crawljob Einstellungen auf Standard zurückgestellt (beides aktiviert)!

**Comment by rix1337** [comment]
Erstmal danke für die Rückmeldung. Kann ich tatsächlich nicht nachstellen.. sowohl auf meinem Server, als auch in der Entwickler-VM.

Bei mir funktionieren beide Speichern-Buttons in verschiedenen Aktiviert/Deaktiviert/Gefüllt/Leer-Konstellationen...

Lösch notfalls nochmal deine RSScrawler.ini und versuch das ganze nochmal. Ansonsten brauche ich Screenshots/den Inhalt deiner Einstellungsdatei oder bestenfalls ein Video!

**Comment by DKeppi** [comment]
Seltsam, denn ich habs auch nach dem Löschen der RSScrawler.ini immer noch :(
Läuft auf einer Synology DS916+ und tritt eben nur beim Speichern Button ganz unten auf...
aber wenn ichs weiß dann klick ich da einfach nimmer drauf, trag ich alles in die ini ein ist es ja da :)

RSScrawler.ini mit verändertem Pushbullet Token anbei.
[RSScrawler.zip](https://github.com/rix1337/RSScrawler/files/1409990/RSScrawler.zip)

**Comment by rix1337** [comment]
Ist behoben. War ein Fehler in der Speicherlogik.. 
https://github.com/rix1337/RSScrawler/commit/0c4f72f03034ef9acfbc170b90e789b96ec4a63c#diff-60432829c418c2c460a5229a5456172dR287

Solange die Videoanzahl nicht auf eine Zahl gesetzt wurde, hat es die änderungen danach verworfen.
