### ISSUE TITLE
Keine Einstellungen mehr

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#132]
Leider ist seit dem neuen Update nun die Weboberfläche plötzlich unvollständig...nach dem Feld Staffeln (Regex) ist Schluss! 
Man kann nicht mehr speichern weil kein Button vorhanden ist und alle Einstellungen sind plötzlich nicht mehr sichtbar...trat erst nach einer Weile auf :(

![f9ca3646-5b0e-4b6e-98c4-526fdd5af618](https://user-images.githubusercontent.com/2063381/31979619-d8e818dc-b947-11e7-90f6-97c245ca433a.jpeg)

**Comment by DKeppi** [comment]
Nachtrag:
Scheint wohl nur auf der legacy Seite zu sein, beim Browser am Windows PC sind die Einstellungen da!

**Comment by rix1337** [comment]
Auch hier brauche ich mal die RSScrawler.ini und bestenfalls die RSScrawler-Seite gespeichert als html-Datei. Wird sicher ein weiterer Bug sein, den ich gerade nicht reproduziert bekomme.

**Comment by DKeppi** [comment]
Anbei die komplette legacy Seite und meine .ini :)

[Website.zip](https://github.com/rix1337/RSScrawler/files/1413674/Website.zip)
[RSScrawler.zip](https://github.com/rix1337/RSScrawler/files/1413679/RSScrawler.zip)

**Comment by rix1337** [comment]
Der war einfach... und peinlich.

**Comment by DKeppi** [comment]
Halb so wild, deswegen teste ich ja!
Super, das ging fix - danke

Eine Kleinigkeit fällt mir noch auf.
Auf der Legacy Seite fehlt der Button "Hilfe zu Regex einblenden" und die Hilfe ist autom. ausgeklappt und wird angezeigt!

Normal:
![image](https://user-images.githubusercontent.com/2063381/31987487-408dcabc-b96c-11e7-826a-7f2c4b09d7de.png)

Legacy:
![image](https://user-images.githubusercontent.com/2063381/31987505-4d6e59c2-b96c-11e7-998c-f04b32e706b9.png)

**Comment by rix1337** [comment]
Das liegt leider daran, dass ich auf der Legacy-Seite auf Java-Script verzichten musste. Bin kein Webentwickler, weswegen mein angepasster Code (bspw. zum ausklappen) nur auf der "echten" Seite funktioniert. Da aber nach den Einstellungen eigentlich eh nur die Listen/der Log interessant sein sollten stört das hoffentlich nicht zu sehr.
Die alternative wäre gewesen, dass die Einstellungen wirklich nur mit Chrome/Firefox benutzbar sind.

Generell ist der Code des Webinterface' furchtbar unordentlich und überladen. Mit bspw. Ruby könnte man das wesentlich eleganter und einfacher pflegen.. da wäre ich aber auf Hilfe angewiesen.
Erstmal ist einfach nur wichtig, dass es läuft.

**Comment by DKeppi** [comment]
Ok, kein Ding...wie du sagst, es stört ja nicht wirklich.
Habe nur auf Unterschiede geachtet ;)

Danke jedenfalls für den schnellen Fix!

Würde dir sofort helfen wenn ich dazu in der Lage wäre, aber bin grad selbst erstmal beim phyton lernen...was schon viel Zeit und Geduld in Anspruch nimmt!

**Comment by rix1337** [comment]
Die Anfangsarbeit hätte ich auch nicht selber gepackt, die habe ich durch einen Freelancer machen lassen. Danach habe ich selbst viel gelernt (python ist dafür echt genial) und der Code ist extrem gewachsen. Vor allem RegEx verstehe ich jetzt deutlich besser. Nach einer Weile musste aber nochmal ein Freelancer ran um den absurd gewachsenen Code per Refactor wieder lesbarer zu machen. Die Nacharbeit habe dann wieder ich übernommen, um wieder die gleichen Funktionen wie vor dem Refactor zu erhalten. Alles in allem ein perfektes Lernprojekt mit privatem Nutzen. Falls du etwas lernen willst, schau einfach mal die Commits bei den größeren Versionssprüngen an (bspw. 1.6 -> 1.9 oder dann eben 2.X auf 3.X) und versuche Schritt für Schritt nachzuvollziehen, was der Code macht.

Frisst aber wie gesagt alles Zeit.. wenn man nicht weiterkommt hilft es, einen Profi zu beauftragen 😄

**Comment by DKeppi** [comment]
Hab mir das alles schon mal etwas angesehen und verstehe auch so manches schon ganz gut, steckt aber wirklich richtig viel Arbeit dahinter! :) Ist aber wie du sagt ein tolles Lernprojekt...
Danke dafür und wenn ich mal weiter bin...wer weiß, viell. kann ich dann sogar mal helfen! :-P
