### ISSUE TITLE
[RSScrawler] Verbesserung IMDB Wertung MB

### ISSUE THREAD

**Issue by feuerwasser85** [rix1337/RSScrawler#133]
Hi rix1337, erstmal Hut ab für die grandiose Arbeit. RSScrawler läuft bei mir auf der Synology 1a!
Ich hätte noch einen bescheidenen Verbesserungsvorschlag:
Den HD-area Pyload Hook kennst du sicher. Dieser konnte nach IMDB Wertung suchen und man konnte einen Schwellwert festlegen. MB bietet das ja auch auf der Seite, sollte also nutzbar sein. Würde mich freuen, wenn Du das umsetzen könntest!
Hier der Link zum damals super funktionierenden Projekt von GutzPilz: https://github.com/Gutz-Pilz/pyLoad-stuff/blob/master/HDAreaOrg.py

**Comment by rix1337** [comment]
Regelverstoß: Kein Code beigetragen

**Comment by rix1337** [comment]
Ist sicher machbar, aber aufwendig. Ich schau mir das nur an, wenn plötzlich viel Zeit vom Himmel fällt.

Ansonsten: einfach mal selber ausprobieren, den Code einzubauen!

**Comment by rix1337** [comment]
https://github.com/rix1337/RSScrawler/tree/imdb_suche

**Comment by rix1337** [comment]
Habe drüber nachgedacht und folgendes begonnen:
[RSScrawler/imdb_suche](https://github.com/rix1337/RSScrawler/tree/imdb_suche)

Einziger Filter wird die IMDB-Wertung (mit Nachkommastelle) sein. Es fehlt noch eine Einbindung in die Einstellungen im Webinterface und eine Weiterreichung per Crawljob.

Folgende Einstellungen schweben mir vor:

0.0 = Deaktiviert
6.0 = Okay
6.9 = Sehenswert
7.4 = Herausragend
7.9 = Pflichtprogramm

Alles unter 6.0 ist typischerweise Trash oder zumindest nur was für "Liebhaber", die Abstufungen darüber sind persönliches Bauchgefühl.

**Comment by rix1337** [comment]
Wunsch erfüllt. IMDB-Suche integriert.
