### ISSUE TITLE
http://tvdb.cytec.us/

### ISSUE THREAD

**Issue by Gutz-Pilz** [rix1337/RSScrawler#14]
http://tvdb.cytec.us/ - das ist ein echt klasse projekt.
soweit ich weiß sogar mit api anbindung - sollte also super sein um aktuelle serien/folgen zu bekommen und diese dann auf serienjunkies zu suchen.
mir kommt es nämlich manchmal so vor, dass der feed lücken auf weist.

Leider ist es noch beta und man muss ne kurze nachricht im forum schreiben um zugang zu bekommen.
wenn du interesse hast, dann gebe ich dir auch gerne mein zugang :)

**Comment by rix1337** [comment]
Coole Sache, nur Zeit das anzubinden habe ich keine.. 
Wer will kann sich daran gerne versuchen.

**Comment by rix1337** [comment]
Da das script jetzt wesentlich weiter entwickelt wurde habe ich issues wieder aktiviert.

Ich habe weiterhin keine Zeit die TVdb anzubinden, aber freue mich über einen entsprechenden PR
