### ISSUE TITLE
[RSScrawler] Hoster-Dropdown inkl. Freitextfeld

### ISSUE THREAD

**Issue by rix1337** [rix1337/RSScrawler#143]
Für den Fall, dass Hoster verschwinden oder nicht-seitenübergreifende Hoster gewünscht sind, die RSScrawler daher nicht unterstützt, sollte der Dropdown um eine Freitext-Option ergänzt werden.

**Comment by DaLeberkasPepi** [comment]
soll dann bei der Freitext Option alle Hoster verwendet werden?

**Comment by rix1337** [comment]
@rix1337 Combobox?
