### ISSUE TITLE
Probleme seit 4.0

### ISSUE THREAD

**Issue by Itsie** [rix1337/RSScrawler#149]
[RSScrawler] Fehlermeldung

  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception                                                              
    reraise(exc_type, exc_value, tb)                                                                                                                     
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request                                                              
    rv = self.dispatch_request()                                                                                                                         
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request                                                                   
    return self.view_functions[rule.endpoint](**req.view_args)                                                                                           
  File "/config/web.py", line 329, in get_post_lists                                                                                                     
    f.write(data['mb']['filme'].encode('utf-8'))                                                                                                         
TypeError: 'NoneType' object has no attribute '__getitem__'           

Fehlerbeschreibung:

Nach Update und Neuinstallation des Docker-Containers sowie auf dem LXC-Container leider die Fehlermeldung, speichern lässt sich auch nichts mehr.

LG Itsie

**Comment by rix1337** [comment]
https://github.com/rix1337/RSScrawler/blob/master/web.py#L329
Die Zeile versucht deine Filme Liste zu speichern.

Kannst du mal deinen Einstellungen Ordner posten?

**Comment by Itsie** [comment]
Natürlich:
https://gyazo.com/41ae685195b5746f879dbfa1b36e1f08


Einstellungen seit dem Start jedoch unverändert:
[RSScrawler]
jdownloader = /rss
port = 9090
prefix =
interval = 3
hoster = Uploaded

[MB]
quality =
ignore =
historical = False
regex = False
cutoff = False
crawl3d = False
enforcedl = False
crawlseasons = True
seasonsquality =
seasonpacks = True
seasonssource = hdtv|hdtvrip|tvrip|web-dl|webrip|webhd|netflix*|amazon*|itunes*|bluray|bd|bdrip
imdbyear = None
imdb = 0.0

[SJ]
quality =
rejectlist =
regex = True

[YT]
youtube = False
maxvideos = 10
ignore =

[Notifications]
pushbullet =
pushover =

[Crawljobs]
autostart = False
subdir = False

**Comment by rix1337** [comment]
Und am besten auch das json, wenn du
Das webinterface + /api/all aufrufst

Ich brauche explizit die listen

**Comment by Itsie** [comment]
[MB_3D.txt](https://github.com/rix1337/RSScrawler/files/1734606/MB_3D.txt)
[MB_Filme.txt](https://github.com/rix1337/RSScrawler/files/1734607/MB_Filme.txt)
[MB_Regex.txt](https://github.com/rix1337/RSScrawler/files/1734608/MB_Regex.txt)
[MB_Staffeln.txt](https://github.com/rix1337/RSScrawler/files/1734609/MB_Staffeln.txt)
[SJ_Serien.txt](https://github.com/rix1337/RSScrawler/files/1734610/SJ_Serien.txt)
[SJ_Staffeln_Regex.txt](https://github.com/rix1337/RSScrawler/files/1734611/SJ_Staffeln_Regex.txt)
[YT_Channels.txt](https://github.com/rix1337/RSScrawler/files/1734612/YT_Channels.txt)

Wo finde ich das "json"?

LG

**Comment by rix1337** [comment]
Bspw. 

http://10.10.0.1:9090/rsscrawler/api/all/

Musst natürlich IP und Port anpassen und ggf den Prefix /rsscrawler entfernen

**Comment by Itsie** [comment]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by rix1337** [comment]
Also ein Problem ist "imdbyear = None" ersetz das mal durch "imdbyear = "

Den Rest schaue ich mir an, wenn ich zu Hause bin.

**Comment by Itsie** [comment]
Hi,

das scheint erstmal zu fruchten, der hat beim "setup" des Dockers auch kein "Einstellungen" Ordner angelegt, selbiges via Debian.

LG

**Comment by rix1337** [comment]
Das Problem konnte ich nachstellen, wird natürlich behoben ^^

**Comment by rix1337** [comment]
Danke fürs Testen.. so ist das leider bei Major Updates, die man alleine testet :P

**Comment by Itsie** [comment]
Super ;) Ja mache ich doch gern, wenn auch unfreiwillig ;) Die Container Station @Qnap hatte nen Update folglich wurde der Docker und das Update  erneut gestartet.

Danke dir erstmal, ich muss mich mal reinlesen, ob man nicht ne QNAP App basteln  kann, muss ja irgendwie gehen ;).

LG

**Comment by rix1337** [comment]
Fixed: https://github.com/rix1337/RSScrawler/commit/ab94638f18653ee501666e1eff392d07201bca9c

Leere Felder behandelt AngularJS wohl als None (statt einen Leeren String "" auszugeben). Habe jetzt eine Handlerfunktion eingebaut, die None in einen leeren String umwandelt.

Außerdem sollte das Script jetzt auch nach Neuinstallation rundlaufen.

Zum Thema QNAP/Synology: 
Mein NAS ist ein selbstgebauter UNRAID-Server (für eine Steam-Streaming-VM/an sich flexibler). Kann also keinen Support dafür anbieten. Dennoch: Immer her damit. Dein Paket müsste eingentlich nur dafür sorgen, dass Python 2.7 die notwendigen Pakete hat (`pip install -r requirements.txt`) und dann (am besten wie mein Dockerfile per git) den Crawler Up2Date halten.

Wenn du ein Paket hast, gib Bescheid. Kommt dann ins Wiki!
