### ISSUE TITLE
Abweichende Auflösung für einzelne Serien

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#151]
Ich habe generell als Auflösung für Serienepisoden 720p ausgewählt. Ist es möglich für einzelne Serien eine abweichende Auflösung (konkret 1080p) einzustellen? Oder muss ich dazu auf RegEx ausweichen?

**Comment by rix1337** [comment]
Genau für den Fall habe ich regex eingebaut :P

**Comment by rix1337** [comment]
Hier ein paar Beispiele:
https://gist.github.com/rix1337/c9e6be8826fb43ecdc75b8da18dd8dc5

**Comment by rix1337** [comment]
Einfach mal auf regexr.com mit ein paar Beispieltiteln ausprobieren.

**Comment by jankete** [comment]
Gegen welche Adresse läuft der Crawler - http://serienjunkies.org/xml/feeds/episoden.xml? Muss ich den Namen der Serie zusätzlich bei "Serien" eintragen oder reicht "Serien (RegEx)? Denn selbst wenn ich mich der Beispiele bediene, bekomme ich kein Ergebnis, obwohl es laut regexr.com eines geben müsste.

**Comment by rix1337** [comment]
Alles unter "SJ" läuft über die expisoden.xml
"MB/SJ" läuft über die staffeln.xml

Und genrell ist RegEx ein entweder/Oder. Wenn du allgemein 720p einstellst und die Serie in die normale Liste packst, findet der crawler die Serie in 720p, wenn du gleichzeitig `Serie.*.1080p.*` in die Regex-Liste packst, findet der Crawler die Serie auch in 1080p.

Wichtig ist nur, dass Regex alle allgemeinen Einstellungen (Filter/Auflösung) ignoriert. Würde die Regex-Liste also nur für Sonderfälle nutzen, wo du Auflösung oder Group bestimmen möchstest.

ps: Links bitte weglassen.

**Comment by rix1337** [comment]
Achso, und ein Titel muss noch im Feed stehen um gefunden zu werden. Das gilt für alle Listen. Ausnahme ist MB. Wenn du dort die Suche (statt Feed) aktivierst, läuft das Script deutlich langsamer, weil es für jeden Listeneintrag alle Sucheinträge abfrühstückt.
