### ISSUE TITLE
[macOS] ImportError: No module named flask

### ISSUE THREAD

**Issue by badrabbit** [rix1337/RSScrawler#152]
Flask ist auf meinem Mac installiert (pip install flask):
/usr/local/bin/flask

Trotzdem lässt sich RSScrawler nicht starten:

> macmini-home-5:RSSCrawler macmini_home$ python RSSCrawler.py
> Traceback (most recent call last):
>   File "RSSCrawler.py", line 52, in <module>
>     from web import start
>   File "/Users/macmini_home/RSSCrawler/web.py", line 1, in <module>
>     from flask import Flask, request, send_from_directory, render_template, jsonify
> ImportError: No module named flask

Irgendwelche Ideen? Muß der Pfad irgendwo noch angepasst werden?

**Comment by rix1337** [comment]
https://github.com/rix1337/RSScrawler/wiki/1.1-Allgemein

Wichtig: Auf macOS müssen die Pakete mittels python -m pip install [MODULNAME] installiert werden!

**Comment by badrabbit** [comment]
Vielen Dank! Funktioniert.

**Comment by rix1337** [comment]
Perfekt. Gerne
