### ISSUE TITLE
[Webinterface] Filterfunktion im Log

### ISSUE THREAD

**Issue by feuerwasser85** [rix1337/RSScrawler#158]
Bei länger werdenden Logs wäre es praktisch, eine Filterfunktion zu haben, in der man das Log auf einzelne Files begrenzen kann. Dies geht zwar auch über STRG+F, dies filtert aber nicht.

**Comment by rix1337** [comment]
Evtl. umsetzbar,.. STRG+F reicht m.E. als Alternative.

Wenn zu komplex: schließen

**Comment by rix1337** [comment]
Kommt in den Ideenspeicher. Vorerst zu aufwändig.

Für die Umsetzung vtml. `ng-filter` nutzen
