### ISSUE TITLE
Update via setup.sh läuft nicht

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#164]
Mein RSScrawler läuft auf 4.0.2 und meldet in der Web-GUI, es wäre ein Update verfügbar. Laut GIT müsste das die 4.0.4 sein.

Wenn ich nun die setup.sh ausführe und "Update" wähle, wird nichts aktualisiert, weil angeblich alles aktuell ist. Beim Update von 4.0.1 auf 4.0.2 hat das noch problemlos geklappt.

> root@raspi3:/opt/RSScrawler# ./setup.sh
> ┌────────────────────────────────────────────────────────┐
>   Programminfo:    RSScrawler v.4.0.2 von RiX
>   Projektseite:    https://github.com/rix1337/RSScrawler
> └────────────────────────────────────────────────────────┘
> Hinweise im Wiki: https://github.com/rix1337/RSScrawler/wiki
> Bitte Plattform wählen:
> 1) Ubuntu/Debian
> 2) Synology
> 3) Update
> 4) Beenden
> #? 3
> Wo ist RSScrawler installiert? Pfad ohne / am Ende: /opt/RSScrawler
> Fordere an von origin
> remote: Counting objects: 53, done.
> remote: Compressing objects: 100% (19/19), done.
> remote: Total 53 (delta 34), reused 51 (delta 34), pack-reused 0
> Entpacke Objekte: 100% (53/53), Fertig.
> Von https://github.com/rix1337/RSScrawler
>    e44bc19..269938b  master     -> origin/master
> Fordere an von rss
> Von https://github.com/rix1337/RSScrawler
>    e44bc19..269938b  master     -> rss/master
> HEAD ist jetzt bei 269938b Merge pull request #163 from rix1337/v.4.0.4
> Von https://github.com/rix1337/RSScrawler
>  * branch            master     -> FETCH_HEAD
> Bereits aktuell.

**Comment by jankete** [comment]
Ich es nun gleich nochmal versucht. Nun schaut es noch schlimmer aus:

> root@raspi3:/opt/RSScrawler# ./setup.sh
> ┌────────────────────────────────────────────────────────┐
>   Programminfo:    RSScrawler v.4.0.4 von RiX
>   Projektseite:    https://github.com/rix1337/RSScrawler
> └────────────────────────────────────────────────────────┘
> Hinweise im Wiki: https://github.com/rix1337/RSScrawler/wiki
> Bitte Plattform wählen:
> 1) Ubuntu/Debian
> 2) Synology
> 3) Update
> 4) Beenden
> #? 3
> Wo ist RSScrawler installiert? Pfad ohne / am Ende: /opt/RSScrawler
> Requirement already up-to-date: bs4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5))
> Requirement already up-to-date: cfscrape in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))
> Requirement already up-to-date: docopt in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 7))
> Requirement already up-to-date: feedparser in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8))
> Requirement already up-to-date: flask in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9))
> Collecting lxml (from -r requirements.txt (line 10))
>   Using cached lxml-4.1.1.tar.gz
> Requirement already up-to-date: requests in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11))
> Collecting beautifulsoup4 (from bs4->-r requirements.txt (line 5))
>   Using cached beautifulsoup4-4.6.0-py2-none-any.whl
> Requirement already up-to-date: PyExecJS>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from cfscrape->-r requirements.txt (line 6))
> Requirement already up-to-date: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt (line 9))
> Requirement already up-to-date: click>=2.0 in /usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt (line 9))
> Requirement already up-to-date: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt (line 9))
> Requirement already up-to-date: Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages (from flask->-r requirements.txt (line 9))
> Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 11))
> Requirement already up-to-date: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 11))
> Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 11))
> Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests->-r requirements.txt (line 11))
> Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from PyExecJS>=1.4.0->cfscrape->-r requirements.txt (line 6))
> Requirement already up-to-date: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.4->flask->-r requirements.txt (line 9))
> Building wheels for collected packages: lxml
>   Running setup.py bdist_wheel for lxml ... error
>   Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mK4B4X/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpIpEkoZpip-wheel- --python-tag cp27:
>   Building lxml version 4.1.1.
>   Building without Cython.
>   ERROR: /bin/sh: 1: xslt-config: not found
> 
>   ** make sure the development packages of libxml2 and libxslt are installed **
> 
>   Using build configuration of libxslt
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-armv7l-2.7
>   creating build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/cssselect.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/__init__.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/builder.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/sax.py -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml
>   creating build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-2.7/lxml/includes
>   creating build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/diff.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/defs.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/builder.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/clean.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-2.7/lxml/html
>   copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml/html
>   creating build/lib.linux-armv7l-2.7/lxml/isoschematron
>   copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-2.7/lxml/isoschematron
>   copying src/lxml/etree.h -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/etree_api.h -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-2.7/lxml
>   copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-2.7/lxml/includes
>   copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-2.7/lxml/includes
>   creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources
>   creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
>   copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
>   creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
>   copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
>   copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
>   creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>   copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>   copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>   copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>   copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>   copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>   copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>   running build_ext
>   building 'lxml.etree' extension
>   creating build/temp.linux-armv7l-2.7
>   creating build/temp.linux-armv7l-2.7/src
>   creating build/temp.linux-armv7l-2.7/src/lxml
>   arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=1 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-armv7l-2.7/src/lxml/etree.o -w
>   In file included from src/lxml/etree.c:619:0:
>   src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: Datei oder Verzeichnis nicht gefunden
>    #include "libxml/xmlversion.h"
>                                  ^
>   compilation terminated.
>   Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
>   creating tmp
>   cc -I/usr/include/libxml2 -c /tmp/xmlXPathInity2Ruv_.c -o tmp/xmlXPathInity2Ruv_.o
>   /tmp/xmlXPathInity2Ruv_.c:1:26: fatal error: libxml/xpath.h: Datei oder Verzeichnis nicht gefunden
>    #include "libxml/xpath.h"
>                             ^
>   compilation terminated.
>   *********************************************************************************
>   Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
>   *********************************************************************************
>   error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
> 
>   ----------------------------------------
>   Failed building wheel for lxml
>   Running setup.py clean for lxml
> Failed to build lxml
> Installing collected packages: lxml, beautifulsoup4
>   Found existing installation: lxml 3.7.1
>     Not uninstalling lxml at /usr/lib/python2.7/dist-packages, outside environment /usr
>   Running setup.py install for lxml ... error
>     Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mK4B4X/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i4wWc0-record/install-record.txt --single-version-externally-managed --compile:
>     Building lxml version 4.1.1.
>     Building without Cython.
>     ERROR: /bin/sh: 1: xslt-config: not found
> 
>     ** make sure the development packages of libxml2 and libxslt are installed **
> 
>     Using build configuration of libxslt
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-armv7l-2.7
>     creating build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/cssselect.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/pyclasslookup.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/ElementInclude.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/__init__.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/builder.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/doctestcompare.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/_elementpath.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/sax.py -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml
>     creating build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/__init__.py -> build/lib.linux-armv7l-2.7/lxml/includes
>     creating build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/_setmixin.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/_html5builder.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/formfill.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/diff.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/defs.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/__init__.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/builder.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/html5parser.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/soupparser.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/clean.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/ElementSoup.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/_diffcommand.py -> build/lib.linux-armv7l-2.7/lxml/html
>     copying src/lxml/html/usedoctest.py -> build/lib.linux-armv7l-2.7/lxml/html
>     creating build/lib.linux-armv7l-2.7/lxml/isoschematron
>     copying src/lxml/isoschematron/__init__.py -> build/lib.linux-armv7l-2.7/lxml/isoschematron
>     copying src/lxml/etree.h -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/etree_api.h -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/lxml.etree.h -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/lxml.etree_api.h -> build/lib.linux-armv7l-2.7/lxml
>     copying src/lxml/includes/xmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/xmlerror.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/xmlschema.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/tree.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/htmlparser.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/config.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/xinclude.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/relaxng.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/__init__.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/uri.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/xslt.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/etreepublic.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/schematron.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/dtdvalid.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/c14n.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/xpath.pxd -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/lxml-version.h -> build/lib.linux-armv7l-2.7/lxml/includes
>     copying src/lxml/includes/etree_defs.h -> build/lib.linux-armv7l-2.7/lxml/includes
>     creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources
>     creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
>     copying src/lxml/isoschematron/resources/rng/iso-schematron.rng -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/rng
>     creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
>     copying src/lxml/isoschematron/resources/xsl/RNG2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
>     copying src/lxml/isoschematron/resources/xsl/XSD2Schtrn.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl
>     creating build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>     copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_dsdl_include.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>     copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_svrl_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>     copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_abstract_expand.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>     copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_message.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>     copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/iso_schematron_skeleton_for_xslt1.xsl -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>     copying src/lxml/isoschematron/resources/xsl/iso-schematron-xslt1/readme.txt -> build/lib.linux-armv7l-2.7/lxml/isoschematron/resources/xsl/iso-schematron-xslt1
>     running build_ext
>     building 'lxml.etree' extension
>     creating build/temp.linux-armv7l-2.7
>     creating build/temp.linux-armv7l-2.7/src
>     creating build/temp.linux-armv7l-2.7/src/lxml
>     arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-kKRR4y/python2.7-2.7.13=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DCYTHON_CLINE_IN_TRACEBACK=1 -Isrc -Isrc/lxml/includes -I/usr/include/python2.7 -c src/lxml/etree.c -o build/temp.linux-armv7l-2.7/src/lxml/etree.o -w
>     In file included from src/lxml/etree.c:619:0:
>     src/lxml/includes/etree_defs.h:14:31: fatal error: libxml/xmlversion.h: Datei oder Verzeichnis nicht gefunden
>      #include "libxml/xmlversion.h"
>                                    ^
>     compilation terminated.
>     Compile failed: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
>     cc -I/usr/include/libxml2 -c /tmp/xmlXPathInitsAU3kU.c -o tmp/xmlXPathInitsAU3kU.o
>     /tmp/xmlXPathInitsAU3kU.c:1:26: fatal error: libxml/xpath.h: Datei oder Verzeichnis nicht gefunden
>      #include "libxml/xpath.h"
>                               ^
>     compilation terminated.
>     *********************************************************************************
>     Could not find function xmlCheckVersion in library libxml2. Is libxml2 installed?
>     *********************************************************************************
>     error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
> 
>     ----------------------------------------
>   Can't rollback lxml, nothing uninstalled.
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-mK4B4X/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-i4wWc0-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-mK4B4X/lxml/
> Fordere an von origin
> Fordere an von rss
> HEAD ist jetzt bei 269938b Merge pull request #163 from rix1337/v.4.0.4
> Von https://github.com/rix1337/RSScrawler
>  * branch            master     -> FETCH_HEAD
> Bereits aktuell.

**Comment by jankete** [comment]
Ich habe die Installation jetzt nochmal sauber "from scratch" gemacht und die Einstellungen zurückgespielt. Jetzt läuft wieder alles.

**Comment by rix1337** [comment]
**Gleich vorweg: die setup.sh ist nur für Ubuntu/Debian oder Synology gedacht. - Raspbian basiert zwar auf debian, nutzt aber eine abweichende CPU-Architektur (arm). Dafür gibt es also keinen Support. Versuchs notfalls von Hand.**

Dann noch zwei Hinweise: dein erster Post sieht einwandfrei aus:
https://github.com/rix1337/RSScrawler/commits/master zeigt genau das
`HEAD ist jetzt bei 269938b Merge pull request #163 from rix1337/v.4.0.4`
der aktuellste commit ist. In dem Fall hat das Update also funktioniert.

Dein zweiter Post zeigt mir nicht ungewöhnliches,.. einziges Problem ist, dass deinem System laut dem letzten Eintrag:
`/tmp/xmlXPathInitsAU3kU.c:1:26: fatal error: libxml/xpath.h: Datei oder Verzeichnis nicht gefunden`
die xpath library fehlt. Google mal notfalls, wie man auf einem arm System (raspbery pi CPU) lxml installiert.. dir fehlt da eine library.

Generell: Ist ja kein Problem den Crawler nochmal neu auzusetzen, solange du den Einstellungen Ordner aufhebst. Schön, dass das geklappt hat :-P

**Comment by rix1337** [comment]
Ergänzung: Auf raspberry pi brauchst du wohl noch:
`sudo apt-get install libxml2-dev libxslt-dev python-dev`
