### ISSUE TITLE
[RSScrawler] Option: Mehrkanalton erzwingen

### ISSUE THREAD

**Issue by 1ne8ight7even** [rix1337/RSScrawler#167]
Would be nice to search by multi channel audio like DTS/DD51/DD71. Sure I can do it via RegEx, but a select would be cool.

**Comment by rix1337** [comment]
Idea is welcome. Not an issue, though.

**Comment by rix1337** [comment]
Its on my "if easy, implement" list. Else RegEx is your friend

**Comment by rix1337** [comment]
@rix1337 `if re.match(r'.*\.(DTS|DD\+*51|DD\+*71|AC3\.5\.*1)\..*', title):`
