### ISSUE TITLE
Synology virtual DSM

### ISSUE THREAD

**Issue by HB19** [rix1337/RSScrawler#172]
# [RSScrawler] Fehlermeldung

I try to run the RSScrawler on my Synology on a virtual machine with a own DSM.
It run fine up to 4.xxxx . Now I get this but don t know how I can solve the problem. 
Can you help ?

/usr/local/lib/python2.7/site-packages/cffi/model.py:526: UserWarning: 'point_conversion_form_t' has no values explicitly defined; next version will refuse to guess which integer type it is meant to be (unsigned/signed, int/long)
  % self._get_c_name())
┌────────────────────────────────────────────────────────┐
  Programminfo:    RSScrawler v.4.0.5 von RiX
  Projektseite:    https://github.com/rix1337/RSScrawler
└────────────────────────────────────────────────────────┘

**Comment by rix1337** [comment]
See: https://github.com/rix1337/RSScrawler/blob/master/ISSUE_TEMPLATE.md

**Comment by rix1337** [comment]
Use docker instead. Saves you the headache...
