### ISSUE TITLE
Pushover Bug seit 4.0.5

### ISSUE THREAD

**Issue by feuerwasser85** [rix1337/RSScrawler#175]
Aktueller Bug seit der 4.0.5:
Der Pushover Service liefert zu jedem gefundenend Ergebnis folgende Meldung:

`RSScrawler: [Episode/RegEx] - {FILENAME} - <a href="{LINK ZU SJ/MB}" target="_blank" title="Link &ouml;ffnen"><i class="fas fa-link"></i></a> <a href="#log" ng-click="resetTitle(&#39;{TITEL}&#39;)" title="Download f&uuml;r n&auml;chsten Suchlauf zur&uuml;cksetzen"><i class="fas fa-undo"></i></a>`

Da wird wohl was nicht korrekt geparsed.
Der Output kommt für alle Suchergebnisse.

**Comment by rix1337** [comment]
Jup. Definitiv ein Bug aus dem aktuellen Loghandling wird gefixt.

**Comment by rix1337** [comment]
Sollte gefixt sein. Bitte um Rückmeldung, falls nicht
