### ISSUE TITLE
Log meldet bei jeder Suche Starting new HTTP connection (1): www.imdb.com/MB.org/SJ.org

### ISSUE THREAD

**Issue by feuerwasser85** [rix1337/RSScrawler#176]
[Einstellungen.zip](https://github.com/rix1337/RSScrawler/files/1803995/Einstellungen.zip)
![image](https://user-images.githubusercontent.com/10442073/37302084-cf133bfc-262a-11e8-81d8-f48981c646c5.png)

Seit Version 4 habe ich das Problem, dass bei jedem Suchlauf das Log mit HTTP connection Meldungen zugemüllt wird. Leider kann ich nicht nachvollziehen, woher das kommt oder wo gesucht werden muss, da die Fehlermeldung keinen Aufschluss gibt.
Aktuell auch bei Version 4.0.5
RSScrawler läuft auf einer Synology NAS

**Comment by rix1337** [comment]
Docker oder nativ?

Sieht aus, wie #166
In dem Fall einfach mal das aktuelle Image ziehen.

Ansonsten installier mal alles aus der aktuellen requirements.txt

**Comment by rix1337** [comment]
Notfalls musst du die RSScrawler.ini löschen und deine Einstellungen frisch aufsetzen.

**Comment by feuerwasser85** [comment]
requirements waren bereits alle installiert. 
`ash-4.3# pip install bs4 cfscrape docopt feedparser flask lxml requests
Requirement already satisfied: bs4 in /usr/lib/python2.7/site-packages (0.0.1)
Requirement already satisfied: cfscrape in /usr/lib/python2.7/site-packages (1.9.4)
Requirement already satisfied: docopt in /usr/lib/python2.7/site-packages (0.6.2)
Requirement already satisfied: feedparser in /usr/local/lib/python2.7/site-packages (5.2.1)
Requirement already satisfied: flask in /usr/lib/python2.7/site-packages (0.12.2)
Requirement already satisfied: lxml in /usr/local/lib/python2.7/site-packages (3.6.0)
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (2.10.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python2.7/site-packages (from bs4) (4.6.0)
Requirement already satisfied: PyExecJS>=1.4.0 in /usr/lib/python2.7/site-packages (from cfscrape) (1.5.1)
Requirement already satisfied: itsdangerous>=0.21 in /usr/lib/python2.7/site-packages (from flask) (0.24)
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python2.7/site-packages (from flask) (2.8)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/site-packages (from flask) (0.11.10)
Requirement already satisfied: click>=2.0 in /usr/lib/python2.7/site-packages (from flask) (6.7)
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/site-packages (from PyExecJS>=1.4.0->cfscrape) (1.11.0)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python2.7/site-packages (from Jinja2>=2.4->flask) (0.23)`
Das Paket läuft bei mir nativ.
Ich versuche mal den Tipp mit der RSScrawler.ini und gebe dann Feedback.

**Comment by rix1337** [comment]
Das sind definitiv nicht alle requirements.

Schau dir die Datei nochmal an.

**Comment by feuerwasser85** [comment]
Ich habe jetzt den RSScrawler völlig neu aufgesetzt und frisch installiert. Leider immernoch selbes Ergebnis. Die HTTP Connection Meldungen kommen wieder.

**Comment by rix1337** [comment]
Okay,.. kannst du mir den gesamten RSScrawler-Ordner zippen?

Dann brauche ich noch infos zu deinem System:
-Welches OS (+ bit)
-Python Version
-Hast du node.js drauf? sollte ohne klappen

Deutsche IP oder VPN (wenn ja, welches Land)

Ich versuche das, so schnell wie möglich nachzustellen...

**Comment by rix1337** [comment]
Eine direkte Rückfrage: Findet die Suche wie gewünscht Titel?

Dh. handelt es sich ausschließlich um einen "kosmetischen" Bug?

Wenn grundsätzlich nur zu viel geloggt wird (jeder requests einfach mal vermerkt), hätte ich eine Idee

@rix1337 `logging.getLogger("requests").setLevel(logging.WARNING)`

**Comment by feuerwasser85** [comment]
[RSScrawler.tar.gz](https://github.com/rix1337/RSScrawler/files/1816756/RSScrawler.tar.gz)
Synology DSM 6.1.5-15254 Update 1
Python 2.7.12
Node.js v4.8.4-0164
Deutsche IP
Die Suche findet wie gewünscht Titel, das ganze ist nur kosmetisch.
Ich denke auch dass hier einfach nur zuviel geloggt wird.
Was ich mir noch vorstellen könnte: Synology Pakete werden auch immer teilweise unter /var/packages installiert. Ich werde mal das Paket deinstallieren und das veraltete Paket neu installieren und updaten. Mal sehen was passiert.

**Comment by rix1337** [comment]
Die Logfunktion an sich steckt schon seit v.0.5 im RSScrawler & hat anscheinend ein paar Probleme.
Werde das bei Zeiten anpassen.

**Comment by rix1337** [comment]
Sollte jetzt gefixt sein. Habe das logging komplett umgebaut
