### ISSUE TITLE
[RSScrawler] Auswahl bei 3D Releases HOU/HSBS

### ISSUE THREAD

**Issue by feuerwasser85** [rix1337/RSScrawler#180]
Schön wäre eine Auswahl bei der 3D Suche, die es erlaubt, zwischen HSBS und HOU auszuwählen. Aktuell wird immer beides gefunden.

**Comment by rix1337** [comment]
Dafür ist die filter Liste da. Schreib einfach hou bzw. hsbs in die Liste bei MB
