### ISSUE TITLE
[RSScrawler] Logging neu aufbauen

### ISSUE THREAD

**Issue by rix1337** [rix1337/RSScrawler#181]
Die Loggingfunktion läuft nicht unter Windows und anscheinend an verschiedenen anderen Stellen ebenfalls nicht rund (#176 etc.)

Daher erforderlich:
-Logeintrag in stdout (Console) **ohne** html
-Logfile inkl. HTML (für Webinterface)
-Logrotate ab ~100 Einträgen (verhindert Crash, falls Log nie händisch geleert wird)
-Default alles auf INFO

**Comment by DaLeberkasPepi** [comment]
hab das gerade noch einmal getestet und wenn ich diesen log verwende kommt das webinterface nicht mehr klar und crasht.
[RSScrawler.log](https://github.com/rix1337/RSScrawler/files/1827098/RSScrawler.log)
