### ISSUE TITLE
Support für DD.tv

### ISSUE THREAD

**Issue by deLuXe83** [rix1337/RSScrawler#183]
Hallo, 
gibt es die Möglichkeit, eigene RSS Feeds hinzuzufügen? Könnte für einige Nutzer interessant sein, denen MB und SJ nicht aussreichen...
Ich denke zB an DD.tv, das funktioniert mit pyload (gibt ein eigens Plugin dafür) ja hervorragend...

**Comment by rix1337** [comment]
Klar. Schau dir einfach eine der Funktionen an die es schon gibt und pass diese auf den gewünschten Feed an.

Das ist idR der größte Aufwand. Es sei denn, die Seitenstruktur ist wie bei MB und HW die gleiche (selber Betreiber, beide WordPress). 

Wenn du den Feed zum Laufen bekommen hast, stell hier einfach einen Pull Request ein.

**Comment by rix1337** [comment]
Wenn es seeehr einfach ist die Seite einzubinden mache ich das evtl. selbst. Verlink einfach das pyload Plugin. Für weitere Fragen: bitte Gitter nutzen.

**Comment by rix1337** [comment]
Erledigt. Frohe Ostern!
