### ISSUE TITLE
Verarbeitung

### ISSUE THREAD

**Issue by Itsie** [rix1337/RSScrawler#186]
Hi,

ich weiss es geht nicht um den Crawler, aber kann mir wer sagen was folgendes zu bedeuten hat:
Apr  3 21:43:12 206a6ad564b8 syslog-ng[9]: syslog-ng starting up; version='3.5.6'                                                                        
Apr  3 21:43:12 206a6ad564b8 syslog-ng[9]: WARNING: you are using the pipe driver, underlying file is not a FIFO, it should be used by file(); filename='
/dev/stdout'                                       

Leider verschiebt er nichts mehr und ich weiss mir da echt nicht zu helfen ;).

LG

**Comment by rix1337** [comment]
Update das image mal.
