### ISSUE TITLE
Search Funktion speichert Serien Link statt Serien Name

### ISSUE THREAD

**Issue by DaLeberkasPepi** [rix1337/RSScrawler#194]
# [RSScrawler] Fehlermeldung
Search Funktion speichert Serien Link statt Serien Name

# Zwingend erforderlich

- **RSScrawler.ini und RSScrawler.db**
[RSScrawler_4.2.0.zip](https://github.com/rix1337/RSScrawler/files/1887932/RSScrawler_4.2.0.zip)

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-install: executing...
Requirement already up-to-date: cfscrape in /usr/lib/python2.7/site-packages
Requirement already up-to-date: requests>=2.0.0 in /usr/lib/python2.7/site-packages (from cfscrape)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Requirement already up-to-date: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests>=2.0.0->cfscrape)
Fetching origin
HEAD is now at cdc1885 v.4.2.0 - Hosterwahl pro Seite/Migration Listen in Datenbank/Besseres Ini-Handling (#192)
From https://github.com/rix1337/RSScrawler
* branch master -> FETCH_HEAD
Already up to date.
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
From https://github.com/rix1337/RSScrawler
* branch master -> FETCH_HEAD
Already up to date.
[cont-init.d] 30-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
┌────────────────────────────────────────────────────────┐
Programminfo: RSScrawler v.4.2.0 von RiX
Projektseite: https://github.com/rix1337/RSScrawler
└────────────────────────────────────────────────────────┘
Docker-Modus: JDownloader-Pfad und Port können nur per Docker-Run angepasst werden!
Nutze das "folderwatch" Unterverzeichnis von "/jd2" für Crawljobs
2018-04-08 23:07:49 - Alle Suchfunktion gestartet.
2018-04-08 23:07:49 - Alle Suchfunktion gestartet.
2018-04-08 23:07:50,274 - [DD] - Englisch - Designated.Survivor.S02E15.1080p.WEB.x264-METCON
2018-04-08 23:08:27 - Alle Suchfunktion ausgeführt (Dauer: 37.4 Sekunden)!
[2018-04-08 23:10:27,053] ERROR in app: Exception on /api/download_sj/11670 [POST]

Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/config/web.py", line 448, in download_sj
if search.sj(id, jdpath):
File "/config/search.py", line 429, in sj
if not title in cont:
TypeError: argument of type 'NoneType' is not iterable
[2018-04-08 23:10:41,461] ERROR in app: Exception on /api/all/ [GET]
```

- **Genutzte Version** (kein Support für alte Releases)
https://github.com/rix1337/RSScrawler/releases/tag/v.4.2.0
# Fehlerbeschreibung:
seit dem letzten Update funktioniert die Suche nicht mehr. Außerdem speichert er in der RSScrawler.db für die Serien in der Tabelle `SJ_Serien` für die Serie `Chance` `· <a href="http://serienjunkies.org/chance/chance-season-1-web-sd720p/">Chance`

Danach funktioniert natürlich die normale Suche alle 10 Minuten nicht mehr weil in `SJ_Serien` jetzt ein Wert steht mit dem er nichts anfangen kann und deswegen auch diese Log Meldung:
```
2018-04-08 23:18:28 - Alle Suchfunktion gestartet.
2018-04-08 23:18:28 - Alle Suchfunktion gestartet.
Traceback (most recent call last):
File "/config/RSScrawler.py", line 130, in crawler
task.periodical_task()
File "/config/RSScrawler.py", line 391, in periodical_task
self.filename, self.level)).lower()
File "/config/RSScrawler.py", line 670, in getSeriesList
sys.argv[0]), "RSScrawler.db"), liste).retrieve()
File "/config/rssdb.py", line 85, in retrieve
items.append(str(r[0]))
```

ich schau mal ob ich morgen mal dahinter komme wo genau der Hund begraben ist, wenn ich den Fehler finde mach ich eh einen PR, aber du weißt wahrscheinlich schon woran es liegen könnte.

**Comment by DaLeberkasPepi** [comment]
Denk mal es hat was mit dem Bereich hier zu tun: https://github.com/rix1337/RSScrawler/blob/cdc18858b6f303df61ef8f9ecb4f39d2b00eb82d/search.py#L416-L431
weil hier wird ja der Return-Wert von der html_to_str Function in die jeweilige Liste in der RSScrawler.db geschrieben. Also entweder stimmt da etwas nicht mehr oder bei der re.findall Funktion für den season_pool string passt schon etwas nicht. 

Aber ich muss mal schauen wie ich diesen Teil am besten testen kann was da gerade schief läuft

**Comment by rix1337** [comment]
Hat nichts mit dem Update zu tun.

Bei Serien mit sehr kurzem Titel macht der Regex zu viel (also auch den href Teil). 

Kannst gerne versuchen den Teil hinter `title` anzupassen.

Es muss dabei ein reiner ASCII string rauskommen. Also alle Umlauten ersetzen und Sonderzeichen löschen

**Comment by DaLeberkasPepi** [comment]
aber eigentlich hat es in der Version davor noch funktioniert und er hat auch die Serien in die richtige Liste geschrieben nur mit dem Namen

**Comment by rix1337** [comment]
Ich kann mir das ab Ende der Woche anschauen, vielleicht findest du in der Zwischenzeit den Fehler.

Lass dir einfach mit Print die variablen in der Suchfunktion ausgeben,.. dadurch findet man den Fehler recht schnell.

Villeicht noch ein Hinweis: wenn durch die Suche ein Titel mit Sonderzeichen oder Umlauten geaddet wird, crasht das Webinterface dann beim Abruf der Listen. Da liegt also noch ein größerer Bug im argen:
Versuch mal `Eine Reihe betrüblicher Ereignisse` zu adden.

Danach musst du bspw. mit dem DB browser for SQLite das ü manuell aus der Liste entfernen.

Trotzdem ist die Datenbankstruktur wesentlich besser im Umgang mit Listeneinträgen (automatisch sortieren, Duplikate entferne, etc.)

**Comment by rix1337** [comment]
Muss also nochmal ran...

**Comment by DaLeberkasPepi** [comment]
wie schon im ersten post geschrieben schreibt er ja nicht `Chance` in die SJ_Serien Tabelle sondern `· <a href="http://serienjunkies.org/chance/chance-season-1-web-sd720p/">Chance` also ein kaputen link. 
Ich schau mir das heute Abend mal an warum er den Link nicht genau erkennt, muss nur schauen das ich nicht ausversehen hinten dran irgend etwas kaput mache weil der Wert vom String `title` wird ja später auch noch verwendet also nicht nur für den Tabelleneintrag. ;)

**Comment by rix1337** [comment]
Hatte wie vermutet nichts mit dem Update zu tun. Die RegEx hat einfach "zu viel" mitgenommen.
