### ISSUE TITLE
No module named wsgi

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#211]
Seit dem Update gestern auf der Synology (6.1.7) startet der RSSCrawler leider nicht mehr.

Python ist definitiv installiert, pip und die requirements wurden installiert, trotzdem kommt der Fehler!

`Traceback (most recent call last):
  File "/volume1/@appstore/RSScrawler-master/RSScrawler.py", line 59, in <module>
    from web import start
  File "/volume1/@appstore/RSScrawler-master/web.py", line 14, in <module>
    from gevent.wsgi import WSGIServer
ImportError: No module named wsgi`

Irgendeine Idee was da falsch läuft?!

**Comment by DKeppi** [comment]
pip list wirft folgendes aus:

`Package         Version
--------------- ---------
beautifulsoup4  4.6.0
bs4             0.0.1
certifi         2018.4.16
cfscrape        1.9.5
chardet         3.0.4
click           6.7
docopt          0.6.2
feedparser      5.2.1
Flask           1.0.2
gevent          1.3.1
greenlet        0.4.13
idna            2.6
itsdangerous    0.24
Jinja2          2.10
lxml            4.2.1
MarkupSafe      1.0
pip             10.0.1
PySocks         1.6.8
python-dateutil 2.7.3
requests        2.18.4
setuptools      39.2.0
six             1.11.0
urllib3         1.22
Werkzeug        0.14.1
wheel           0.31.1`

**Comment by DKeppi** [comment]
Ich habs gelöst...es kann so einfach sein!!!!

In der web.py gehört in die Zeile 14 anstatt des 
from gevent.wsgi import WSGIServer
ein
from gevent.pywsgi import WSGIServer

Es läuft wieder!

Kannst du das korrigieren?

**Comment by rix1337** [comment]
Es sollte beide geben, wobei wsgi schneller ist als pywsgi. Das sieht unwesentlich aus, daher baue ich die Änderung ein. Sollte es zu Problemen kommen, muss eine andere Lösung her.

http://blog.pythonisito.com/2012/08/building-web-applications-with-gevents.html

**Comment by DKeppi** [comment]
Dankeschön :)

Vor 6.1.7 gings definitiv noch...
