### ISSUE TITLE
Docker Parameter

### ISSUE THREAD

**Issue by Gutz-Pilz** [rix1337/RSScrawler#266]
Hi rix,

erstmal mega, dass du immernoch so stark daran arbeitest und immernoch features erweiterst!

Ich kann den Docker nicht wirklich starten.
Es scheint so, dass er die Parameter nicht an die RSSCrawler.py weitergibt.
Kannst du das checken und ggf. eine Beispiel docker-compose auflisten.
zumindest den teil in "environment" um die Paramter weiter zu geben.

Danke dir!!

**Comment by rix1337** [comment]
Gerne,.. dein Lob ehrt mich 👍. Ohne pyLoad und die Userscripte wären wir heute nicht hier.

Ich nutze den integrierten Docker client von UnRAID. Daher kann ich nicht mit einer Docker compose dienen.

Das Wiki ist nicht ganz aktuell. Die notwendigen RUN-Befehle findest du aber im Docker hub:
https://hub.docker.com/r/rix1337/docker-rsscrawler/

Folgender Run-Befehl sollte funktionieren, wenn du nur einen JDownloader hast. Ansonsten muss noch `--jd-device` mitgegeben werden.

`docker run -d --name='RSScrawler' --net='bridge' -e 'LOGLEVEL'='INFO' -e 'PARAMETER'='--jd-user=<NUTZERNAME> --jd-pass=<PASSWORT>' -p '9090:9090/tcp' -v '/mnt/cache/appdata/rsscrawler/':'/config':'rw' 'rix1337/docker-rsscrawler' `

Alternativ installierst du das Script lokal, konfigurierst alles über die Konsole und legst die RSScrawler.ini dort ab, wo du `/config` mountest. `-e PARAMETER` benötigtst du nur für den ersten Start.

**Comment by rix1337** [comment]
Ich habe den Anlass genutzt und das Wiki überarbeitet:
https://github.com/rix1337/RSScrawler/wiki/1.3-Docker

**Comment by Gutz-Pilz** [comment]
geht leider immernoch nicht.
habe auch versucht die quotes zu escapen.

kannst du bitte eine beispiel.ini bereitstellen. meine Alte ini ist noch ohne myjd anbindung

**Comment by rix1337** [comment]
Die alte Wiki muss funktionieren. Dann einfach per webinterface die myjd Daten speichern

**Comment by Gutz-Pilz** [comment]
Alles klar. Hab das im Webitnerface nicht gegen gecheckt. 

```
Exception on /api/myjd/ [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 429, in myjd_info
    myjd = get_info(configfile, device)
  File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 289, in get_info
    packages_in_downloader = get_packages_in_downloader(device)
  File "/usr/lib/python3.6/site-packages/rsscrawler/myjd.py", line 124, in get_packages_in_downloader
    for link in links:
TypeError: 'bool' object is not iterable

```

**Comment by rix1337** [comment]
Das ist ein Bug. Wird im nächsten Release behoben.

Danke auch für die Meldung allgemein. Ich habe den Docker-Start nachgebessert - ebenfalls im kommenden Release.
