### ISSUE TITLE
KeyError Path

### ISSUE THREAD

**Issue by DaLeberkasPepi** [rix1337/RSScrawler#274]
> KeyError: 'path'
>     if subdir and 'RSScrawler' in op['path']:
>   File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 669, in myjd_cnl
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     raise value
>   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> Traceback (most recent call last):
> 2018-11-15 22:02:58,921 - Exception on /api/myjd_cnl/1542314066388 [POST]
> KeyError: 'path'
>     if subdir and 'RSScrawler' in op['path']:
>   File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 669, in myjd_cnl
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     raise value
>   File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     response = self.full_dispatch_request()
>   File "/usr/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
> Traceback (most recent call last):
> 2018-11-15 22:00:37,441 - Exception on /api/myjd_cnl/1542314066388 [POST]
> 2018-11-15 21:34:26,812 - [IMDB 8.3/Film] - A.Star.Is.Born.German.DL.AC3.Dubbed.1080p.WEBRip.x264-PsO

der Fehler kommt jedesmal wenn ich den Film "A.Star.Is.Born" per CnL hinzufügen will. Ich hab beim zweiten versuch auch schon die neueste Version v.5.2.15 verwendet.

Hier noch eine Zip mit meiner .db und den logs. Die ini habe ich nicht wegen Passwörtern usw geaddet. Falls du die auch brauchst einfach melden. Übrigends Unterordner sind da schon aktiviert gewesen.
[RSSCrawler.zip](https://github.com/rix1337/RSScrawler/files/2587053/RSSCrawler.zip)

**Comment by rix1337** [comment]
Schau ich mir am Wochenende an. Danke für die Meldung.

**Comment by rix1337** [comment]
Bitte stell dazu deine aktuellen Links aus dem JDownloader als DLC zur Verfügung.
