### ISSUE TITLE
Seit 5.2.15 plötzlich viele unerklärliche Crawls

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#275]
Seit dem Update auf 5.2.15 müllt es mir den Linksammler voll bzw. wegen dem autom. Download hat es 100 GB in der Nacht geladen - jetzt ist der Shareonline Account mal offline weil ich das Tageslimit erreicht habe. Zudem hats mir bei 9kw natürlich etliche Captchasolves abgezogen :(

Meine Listen sind alle leer und trotzdem wird was gefunden?!
Hab sogar das imdbyear mal auf 2019 gestellt

Debug log und ini anbei!
Meine Logins habe ich entfernt und der autom. Download steht momentan mal auf False
[RSScrawler_DEBUG.log](https://github.com/rix1337/RSScrawler/files/2588139/RSScrawler_DEBUG.log)
[RSScrawler.ini.txt](https://github.com/rix1337/RSScrawler/files/2588170/RSScrawler.ini.txt)

**Comment by rix1337** [comment]
Danke für die Meldung. Das muss ich mir am Wochenende ansehen.

Die MB Suche hat bisher eine recht überladene Methode zum suchen verwendet. Nach meinen Tests sollte die Anpassung eigentlich nicht so unerwartet laufen. Ziel ist die Suche sauber zu bekommen.....

**Comment by Gutz-Pilz** [comment]
hier das selbe
Vorallem Regex macht probleme

**Comment by DKeppi** [comment]
Ich lösche mal meine ini und stelle alles neu ein, ein Kollege hat das nicht.
Er hat kein Jahr in der IMDB Suche und Regex = false
Mal sehen...

**Comment by rix1337** [comment]
2 Lektionen: 

Das Docker Image braucht eine "folgende Version installieren" Funktion

Wenn ihr nicht docker nutzt kann per pip auch die 5.2.14 wieder installiert werden....

**Comment by DKeppi** [comment]
Kollege war noch nicht auf 5.2.15 ;) Jetzt klingelts bei ihm auch...

**Comment by rix1337** [comment]
Hab erstmal die Anpassung zurück gerollt. Zum Testen benötige ich möglichst alle eure DBs/Logs aus der 5.2.15.

Die Blogs-Suche hat anscheinend noch mehr Fehler,.. bei mir läuft die zum Teil 20 Minuten lang...

Am schluss haben wir aber ein besseres Produkt.

**Comment by DKeppi** [comment]
Kannst du beim Docker Container auch einen Rollback machen oder geht das nicht?!

**Comment by rix1337** [comment]
Einfach neustarten.

**Comment by DaLeberkasPepi** [comment]
Lustigerweise schein ich das Problem mit der Version nicht zu haben. Zumindest bekomme ich keine Pushbullet Benachrichtigungen damit.
