### ISSUE TITLE
RSS Ordner im Release Ordner

### ISSUE THREAD

**Issue by graschbaten** [rix1337/RSScrawler#292]
@rix1337 Ich hatte das Thema schon einmal angesprochen dies aber wieder aus den Augen verloren. Daher habe ich mal einen Screenshot gemacht um dies etwas leichter erklären zu können. https://i.imgur.com/gyTZ7Xv.png Vor einigen Versionen war es so das sich alle Downloads im RSScrawler Ordner befanden nun ist dieser unter dem Release Ordner. Nachteil: Nach erfolgreichen Entpacken kann der Release Ordner nicht mehr gelöscht werden da dort noch der RSScrawler drin befindet. Vielleicht kannst du da ja mal rüber schauen

ps: Auch wenn ich es jetzt ungern gezipt habe aber die *.ini und*.dtb wollte Github nicht aktzeptieren
[Archiv.zip](https://github.com/rix1337/RSScrawler/files/2989303/Archiv.zip)

**Comment by rix1337** [comment]
Wenn ich Zeit finde, schau ich mir das mal an. Ich habe festgestellt, dass nicht jeder JDownloader die Unterpfade richtig schluckt...

**Comment by graschbaten** [comment]
Hallo Rix1337,

vielen Dank für die Rückmeldung.
Als kleine Info: Ich nutze den https://hub.docker.com/r/jlesage/jdownloader-2/ <https://hub.docker.com/r/jlesage/jdownloader-2/> Docker unter unRaid

Mit Grüßen Christian

**Comment by rix1337** [comment]
Hi, ich konnte das Verhalten auch nach langwierigem ausprobieren nicht nachstellen.
JDownloader geht allerdings auf Windows mit Pfaden anders um, als unter Linux.
Wie und warum ist allerdings nirgends dokumentiert.

Mit deiner Ini und deiner DB funktioniert der Unterordner im aktuellen Release jedenfalls wie erwartet mit meinem Unraid-Jdownloader-Container
