### ISSUE TITLE
Darstellung falscher Sucheinträge

### ISSUE THREAD

**Issue by Erik262** [rix1337/RSScrawler#296]
Hallo,

vergibt man in den Einstellungen in SJ bzw. Blogs/SJ als Auflösung 1080p ein, werden in der Suche nur die 720p Versionen angezeigt. Wird in der Suche auf "Serie: XYZ" geklickt erscheinen in den Logs die korrekten 1080p Versionen. 
Kurzgesagt: Übereinstimmen die Suchkriterien nicht mit den Einstellungen überein (jedenfalls bei mir nicht)

- Version 5.5.2
- Problem lässt sich reproduzieren.

**Comment by rix1337** [comment]
Moin, das beschriebene Verhalten kann ich nicht nachstellen.

Blogs, SJ, Blogs/SJ auf 1080p gestellt. Suchfeld im Webinterface benutzt. Alle Ergebnisse sind in 1080p.

**Comment by rix1337** [comment]
# Zwingend erforderlich

- **RSScrawler.ini und RSScrawler.db als Datei**

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

- **Genutzte Version** (kein Support für alte Releases)

- **Wird Python 3.6 oder aktueller genutzt?**
