### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/RSScrawler#321]
# [RSScrawler] Fehlermeldung

Hier keine Kontaktaufnahme, dafür gibt es:
https://gitter.im/RSScrawler/Lobby

# Zwingend erforderlich

- **RSScrawler.ini und RSScrawler.db als Datei**

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

- **Genutzte Version** 5.7.3

- **Wird Python 3.6 oder aktueller genutzt?** 3.7.0

# Fehlerbeschreibung:

[Suche/Film] - Taxi.Driver.1976.German.720p.BluRay.x264-DETAiLS
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rsscrawler/RSScrawler.py", line 120, in crawler
    device = ombi(configfile, dbfile, device, log_debug)
  File "/usr/local/lib/python3.7/site-packages/rsscrawler/ombi.py", line 174, in ombi
    infos = tvdb(configfile, dbfile, tvdbid, tvd_user, tvd_userkey, tvd_api)
  File "/usr/local/lib/python3.7/site-packages/rsscrawler/ombi.py", line 48, in tvdb
    headers={'Authorization': 'Bearer ' + token, 'Content-Type': 'application/json',
TypeError: can only concatenate str (not "NoneType") to str

**Hier keine Links posten. Die Seiten heißen MB bzw. SJ!**

**Comment by rix1337** [comment]
Grund sind falsche Zugangsdaten für die TVDB.

Der Fehler sollte nicht zum Programmabruch führen, das wird in der nächsten Version gefixt.

**Comment by rix1337** [comment]
Ab sofort weist das Debug-Log auf fehlerhafte TVDB-Zugangsdaten hin. Der restliche Crawler läuft weiter.
