### ISSUE TITLE
Layout im mobilen Browser 

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#340]
**Genutzte Version**
6.0.3 im Docker unter Ubuntu

# Fehlerbeschreibung:

Im mobilen Browser (Chrome) unter Android, wird das Layout an einigen Stellen vom Text gesprengt. (z.B. bei den Suchergebnissen oder den Einstellungen bei den Blogs/Feeds)

![Screenshot_20191027-134657~2](https://user-images.githubusercontent.com/22338766/67634858-326ea780-f8c1-11e9-9f42-dd0429ee1e76.png)
![Screenshot_20191027-134733~2](https://user-images.githubusercontent.com/22338766/67634864-3b5f7900-f8c1-11e9-84cb-7f384f1f209f.png)

**Comment by rix1337** [comment]
Das mit den Überschriften wird schon in 6.0.4 behoben, das mit den Suchergebnissen ist mir neu.
Danke für die Meldung!
