### ISSUE TITLE
Text überlagert Layout

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#342]
**Genutzte Version**
6.0.5 im Docker unter Ubuntu

# Fehlerbeschreibung:

Issue #340 ist nur zum Teil gelöst. Die Suchergebnisse sind jetzt sauber.

Aber:
Im Browser (z.B. Chrome) unter Windows & Android, wird das Layout an einigen Stellen noch immer vom Text gesprengt. (z.B. bei den Einstellungen bei den Blogs/Feeds)

![2019-10-29 09_51_33-Window](https://user-images.githubusercontent.com/22338766/67751839-2524fa80-fa32-11e9-9a33-cb4cef9f214c.png)
![2019-10-29 09_52_00-Window](https://user-images.githubusercontent.com/22338766/67751840-2524fa80-fa32-11e9-8408-b4c92ffdc2cc.png)

**Comment by rix1337** [comment]
Nicht nachstellbar, Chrome und Firefox stellen den Text in allen Bildschirmgrößen korrekt dar.
Lösch mal deinen Browsercache.

**Comment by jankete** [comment]
Du hast Recht, nach leeren des Caches passt es. Danke!

**Comment by rix1337** [comment]
Perfekt und danke für die schnelle Meldung.

Schau auch ruhig, ob die Schrift mobil noch lesbar ist - musste die dynamisch kleiner werden lassen, damit alles reinpasst und kann da noch nachbessern.
