### ISSUE TITLE
Keine Verbindung zum jDownloader 2

### ISSUE THREAD

**Issue by graschbaten** [rix1337/RSScrawler#346]
# [RSScrawler] Fehlermeldung

Dieser Bereich dient der Fehlermeldung.

Für Rückfragen und Chat gibt es:
https://gitter.im/RSScrawler/Lobby

# Zwingend erforderlich

- **RSScrawler.ini** (Zugangsdaten entfernen) **und RSScrawler.db als Datei**
RSScrawler.in
https://mega.nz/#!TAlVDQKL!dUDkZA0vFSxS1bXIeI_a0_nRoMa2mgi6-OCUS8W37FE

RSScrawler.db
https://mega.nz/#!PcthwA7R!EMzR2a_nvDq8PyxVzLo43QrFwZ5a0ZwqkZAbID2IPTc
- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
Log
https://mega.nz/#!TRsDFKpQ!ynDCatci21js-CpexV-3PP8AunrVLB4z76pTEjQ1LnQ

- **Genutzte Version** (kein Support für alte Releases)
v.6.0.8

- **Wird Python 3.7 oder aktueller genutzt?**
unRaid Docker template

# Fehlerbeschreibung:

Nach dem Dockerupdate auf Version v.6.0.8 über das unRaid template kann der RSScrawler keine Verbindung mehr zum jDownloader 2 aufbauen. selbstverständlich ist der jDownloader mit myjDownloader verbunden.

Ich nutze das jDownloader Image von jlesage/jdownloader-2

**Comment by rix1337** [comment]
@graschbaten Danke fürs gute Issue - sollte nicht mehr auftreten
