### ISSUE TITLE
[Feature Request] Retail Only Option

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#383]
Es wäre schön, eine Option zu haben, um ausschließlich Retails bei der automatischen Filmsuche zu berücksichtigen. Damit könnten Vorabversionen ignoriert und der gleiche Film würde in Kombination mit der vorhandenen Retail Option bestenfalls nur 1x heruntergeladen werden.

**Comment by rix1337** [comment]
Behoben in Version 6.6.0
