### ISSUE TITLE
Fehler nach Docker update (unraid 6.8.2)

### ISSUE THREAD

**Issue by mx-hero** [rix1337/RSScrawler#384]
# [RSScrawler] Fehlermeldung

┌──────────────────────────────────────────────┐
RSScrawler v.6.5.4 von RiX
https://github.com/rix1337/RSScrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Ein unbekannter Fehler in der Konfigurationsdatei ist aufgetreten.
Traceback (most recent call last):
File "/usr/bin/rsscrawler", line 8, in <module>
sys.exit(main())
File "/usr/lib/python3.6/site-packages/rsscrawler/crawler.py", line 345, in main
rsscrawler = RssConfig('RSScrawler', configfile)
File "/usr/lib/python3.6/site-packages/rsscrawler/rssconfig.py", line 110, in __init__
self._config.read(self._configfile)
File "/usr/lib/python3.6/configparser.py", line 697, in read
self._read(fp, filename)
File "/usr/lib/python3.6/configparser.py", line 1092, in _read
fpname, lineno)
configparser.DuplicateOptionError: While reading from '/config/RSScrawler.ini' [line 20]: option 'shorter_cnl_timeout' in section 'RSScrawler' already exists

Für Rückfragen und Chat gibt es:
https://gitter.im/RSScrawler/Lobby

**Comment by rix1337** [comment]
# Zwingend erforderlich

- **RSScrawler.ini** (Zugangsdaten entfernen) **und RSScrawler.db als Datei**

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

- **Genutzte Version** (kein Support für alte Releases)

- **Wird Python 3.7 oder aktueller genutzt?**
