### ISSUE TITLE
[Feature Request] NK

### ISSUE THREAD

**Issue by Slomo17** [rix1337/RSScrawler#387]
Ich würde mich über die aufnahme von der Seite NK in die blogs freuen.

~Zweitens wäre es cool, wenn man bei Serienjunkies (oder auch den warez blogs), einstellen könnte, dass er automatisch immer die besste qualität läd, die er findet.~ @rix1337: der zweite Wunsch ist nicht machbar, da der Crawler immer nur auf einzelne Titel schaut, es gibt kein "Wissen" über andere Titel im Feed, und entsprechend kann keine "nimm das beste" Auswahl erfolgen.

**Comment by rix1337** [comment]
@Slomo17 NK ist ab v.6.6.4 verfügbar. Viel Spaß damit 👍 

Der zweite Teil wird technisch nix.

**Comment by Slomo17** [comment]
Cool, vielen Dank
