### ISSUE TITLE
[Bug] Log in Chromium nicht horizontal scrollbar

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#399]
# [RSScrawler] Feature Request

- **Genutzte Version** (kein Support für alte Releases)
6.6.7

- **Wird Python 3.7 oder aktueller genutzt?**
Docker Container

# Fehlerbeschreibung:
Das Log im Frontend, ist auf dem Smartphone nicht horizontal scrollbar. Dadurch sind die Einträge abgeschnitten, da sie auch nicht umgebrochen werden. Eventuell lässt sich in einem zukünftigen Release berücksichtigen.

![Screenshot_20200415-193602](https://user-images.githubusercontent.com/22338766/79369442-41b9de00-7f51-11ea-9bf8-5439265a4c0c.png)

**Comment by rix1337** [comment]
Der log ist bei mir horizontal scrollbar? Leer mal deinen Browsercache und versuch es erneut.

**Comment by jankete** [comment]
Habe ich versucht, leider ohne Erfolg. Keine Scrollbar und auch keine Aktion beim "Wischen".

Browser ist der aktuelle Chrome unter Android 10.

Ergänzung: Unter Firefox tritt das Problem nicht auf.

**Comment by rix1337** [comment]
Dann muss ich es nochmal mit Chrome versuchen. Bin Alter Firefox hase .. danke fürs Issue. Arbeite eh an der 6.6.8 um die Cloudscraper Warnungen zu unterdrücken.

**Comment by rix1337** [comment]
Ist ein allgemeines Problem mit Chromium Browsern.
