### ISSUE TITLE
Nach Update Web UI nicht mehr erreichbar

### ISSUE THREAD

**Issue by graschbaten** [rix1337/RSScrawler#413]
# [RSScrawler] Fehlermeldung

Dieser Bereich dient der Fehlermeldung.

Für Rückfragen und Chat gibt es:
https://gitter.im/RSScrawler/Lobby

# Zwingend erforderlich

- **RSScrawler.ini** (Zugangsdaten entfernen) **und RSScrawler.db als Datei**
                                                  
[MB]
quality = 2160p
search = 10
ignore = cam,subbed,xvid,dvdr,avc,pal,md,ac3md,mic,xxx,x265,x264,h264,h265
regex = True
cutoff = False
crawl3d = False
crawl3dtype = hsbs
enforcedl = False
crawlseasons = True
seasonsquality = 720p
seasonpacks = True
seasonssource = web-dl.*-(tvs|4sj)|webrip.*-(tvs|4sj)|webhd.*-(tvs|4sj)|netflix.*-(tvs|4sj)|amazon.*-(tvs|4sj)|itunes.*-(tvs|4sj)|bluray|bd|bdrip
imdbyear = 1975
imdb = 4.5
hoster_fallback = True
hevc_retail = False
retail_only = False

[SJ]
quality = 720p
rejectlist = xvid,subbed
regex = False
hoster_fallback = True

[DJ]
quality = 720p
rejectlist = xvid,subbed
regex = False
genres = .*
hoster_fallback = False

[DD]
feeds =.
hoster_fallback = False

[YT]
youtube = False
maxvideos = 10
ignore =.

[RSScrawler]
auth_user =.
auth_hash =.
myjd_user =.
myjd_pass =.
myjd_device =.
port = 9090
prefix =.
interval = 10
english = False
surround = False
proxy =.
fallback = False
closed_myjd_tab = False
one_mirror_policy = False
packages_per_myjd_page = 3

[Hosters]
rapidgator = True
turbobit = False
uploaded = False
zippyshare = False
oboom = False
ddl = False
filefactory = False
uptobox = False
 1Help           2Save           3Mark           4Replac         5Copy           6Move           7Search         8Delete         9PullDn        10Quit

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

- **Genutzte Version** (kein Support für alte Releases)

- **Wird Python 3.7 oder aktueller genutzt?**

# Fehlerbeschreibung:

Nach dem aktuellsten Update des des RssCrawler Dockers ist es nicht mehr möglich auf die Webui zu kommen. Außerdem endecke ich gerade das meine Rsscrawler.ini zurückgesetzt worden ist da nichts eingetragenes enthalten ist.
Mein Debuglog sagt:
───────────┐
RSScrawler v.6.8.1 von RiX
https://github.com/rix1337/RSScrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Bitte die Zugangsdaten für My JDownloader angeben:
Traceback (most recent call last):
File "/usr/bin/rsscrawler", line 8, in <module>
sys.exit(main())
File "/usr/lib/python3.6/site-packages/rsscrawler/crawler.py", line 338, in main
arguments['--jd-pass'], arguments['--jd-device'])
File "/usr/lib/python3.6/site-packages/rsscrawler/files.py", line 52, in myjd_input
user = input("Nutzername/Email:")
EOFError: EOF when reading a line
Nutzername/Email:┌──────────────────────────────────────────────┐

**Comment by rix1337** [comment]
Der crawler findet die Einstellungen nicht. Bis zum Webinterface kommt er gar nicht, da der Start abgebrochen wird.

Sicher, dass der Container Zugriff auf /config deinens Docker Hosts hat?

**Comment by graschbaten** [comment]
Danke für die Info!
Beim Update hat es mir wohl die ini zerschossen..

Gott sei Dank hatte ich noch ein Backup.
