### ISSUE TITLE
Crawler startet nicht

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/RSScrawler#417]
# [RSScrawler] Fehlermeldung

`[~] # rsscrawler
/opt/lib/python3.8/site-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.9) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/opt/bin/rsscrawler", line 5, in <module>
    from rsscrawler.crawler import main
  File "/opt/lib/python3.8/site-packages/rsscrawler/crawler.py", line 45, in <module>
    from rsscrawler import files
  File "/opt/lib/python3.8/site-packages/rsscrawler/files.py", line 8, in <module>
    from rsscrawler.myjd import get_device
  File "/opt/lib/python3.8/site-packages/rsscrawler/myjd.py", line 8, in <module>
    from rapidfuzz import fuzz
  File "/opt/lib/python3.8/site-packages/rapidfuzz/__init__.py", line 4, in <module>
    from rapidfuzz import process, fuzz, levenshtein, utils
  File "/opt/lib/python3.8/site-packages/rapidfuzz/process.py", line 5, in <module>
    from rapidfuzz import fuzz, utils
ImportError: cannot import name 'fuzz' from partially initialized module 'rapidfuzz' (most likely due to a circular import) (/opt/lib/python3.8/site-packages/rapidfuzz/__init__.py)
`
Für Rückfragen und Chat gibt es:
https://gitter.im/RSScrawler/Lobby

# Zwingend erforderlich

- 6.8.4

- Python 3.8.1

- QNAP mit Entware

# Fehlerbeschreibung:

Nach einem Package update und damit upgrade auf python 3.8 wurde der crawler hier nochmal neu installiert.
Leider bekomme ich seit dem immer diese Fehlermeldung.
Ich habe noch nicht genauer eingrenzen können wo es her kommt.

Aktuell sind die aktuellsten Versionen installiert der Pakete auch rapidfuzz 0.9.1.
Aber auch ein downgrade auf rapidfuzz 0.4.0 mit dem der crawler zuvor lief löste das Problem nicht und es kam nur ein anderer Fehler das ein Paket nicht gefunden wurde.

**Comment by rix1337** [comment]
Das Problem hat laut Fehlermeldung nichts mit RSScrawler zu tun.

**Comment by rix1337** [comment]
Versuch es bitte mit dem Docker Image, `pip install -I -U rsscrawler` oder einer Fehlermeldung im rapidfuzz Projekt.

**Comment by 9Mad-Max5** [comment]
Das habe ich mir fast schon gedacht aber habe aktuell keinen wirklichen besseren ansatz.
Welche versionen verwendest du? Auch Python 3.8?

**Comment by 9Mad-Max5** [comment]
Scheint ein Problem zwischen python 3.8 und in den anderen Paketen zu sein. Habe jetzt den docker erfolgreich am laufen

**Comment by rix1337** [comment]
Hm, ich nutze zum bauen python 3.8. Aber im zweifel garantiert docker eine Lauffähige Umgebung!

**Comment by 9Mad-Max5** [comment]
Ja das klappt, auf jeden fall mal. Was hast du bei pip list als Abhängigkeiten drin? 
Ich befürchte das die Versionen Ärger machen.
Ich habe alle Versionen auf die des dockers gezogen bis auf diese 3:
`cffi              1.12.2
lxml              4.2.5
Pillow            5.4.1`

**Comment by rix1337** [comment]
lxml brauchst du sehr sicher, und cffi ist meines Wissens eine Abhängigkeit von den Crypto Bibliotheken. Ob pillow nötig ist...

**Comment by 9Mad-Max5** [comment]
Installiert habe ich sie schon aber in neueren Versionen als im Docker.
`cffi              1.14.0
lxml              4.5.1
Pillow            7.1.2`
Das sind meine Versionen
