### ISSUE TITLE
Unterstützung für SF

### ISSUE THREAD

**Issue by Slomo17** [rix1337/RSScrawler#427]
Aufgrund eines Streits zwischen den Betreibern gibt es von SJ eine Abspaltung namens SF, die meiner meinung nach besser aussieht als Serienjunkies. Wäre es möglich diese zu unterstützen?

**Comment by rix1337** [comment]
Gute Idee. Wird allerdings eine Weile dauern und vmtl. nur in Verbindung mit dem Sponsors Helper laufen.
Die neue Seite nutzt cloudflare und eine recht gut abgesicherte API.

**Comment by rix1337** [comment]
Erledigt ;) #429
War einfacher als gedacht.

**Comment by rix1337** [comment]
Danke für den Hinweis!

**Comment by Slomo17** [comment]
Oh das ging ja schnell, super, vielen Dank
