### ISSUE TITLE
SF hat die Serien-API angepasst. Breche Download-Prüfung ab!

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#431]
# [RSScrawler] Fehlermeldung

SF hat die Serien-API angepasst. Breche Download-Prüfung ab!

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
SF hat die Serien-API angepasst. Breche Download-Prüfung ab!

- **Genutzte Version** (kein Support für alte Releases)
8.0.2 via Docker

- **Wird Python 3.7 oder aktueller genutzt?**
Docker-Image

## Fehlerbeschreibung
Die neue Implementierung von SF scheint leider nicht zu funktionieren. Im Log findet sich nur der o.g. Hinweis dazu.

**Comment by rix1337** [comment]
Da fehlen mehr Infos, bei mir klappt es wunderbar. Schreib mir mal auf gitter.

**Comment by rix1337** [comment]
Danke für die Fehlermeldung. Ist gelöst!
