### ISSUE TITLE
Keine direkte MyJDownloader anbindung mehr?

### ISSUE THREAD

**Issue by Slomo17** [rix1337/RSScrawler#452]
Hallo,

Ich habe RSSCrawler früher viel genutzt, jetzt seit einiger zeit aber nicht mehr und bin verwirrt, wie das jettz funktioniert und finde im Wiki dazu nichts. Es sagt mir dauernd ich soll irgendwelche addons intallieren. Gibt es keine direkte Myjdownloader mehr wie es früher mal was? gibts noch ne möglichkeit das über den watch folder von jdownloader zu machen?

**Comment by rix1337** [comment]
Watch folder ist seit sehr langer Zeit nicht mehr dabei (kommt auch nicht wieder), weil große Teile des Download handlings mittlerweile direkt mit dem JDownloader sprechen müssen.

Nimm dir einfach die Zeit das in Ruhe einzurichten. Zweite große Änderung ist, dass die Hostnamen manuell eingetragen werden müssen. Welche erfährst du nicht von mir.

Sollte dann alles ordentlich laufen ;)

**Comment by rix1337** [comment]
Vielleicht hilft dir wer im Gitter chat
