### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by gadric** [rix1337/RSScrawler#453]
Does an integration of Signal Messenger make sense? I see more and more project integration signal messenger. 

If you combine this with [signal-cli-rest-api](https://github.com/bbernhard/signal-cli-rest-api), this should be quite easy, as it is more or less an curl HTTP post request.

**Comment by rix1337** [comment]
Sure, but I am not using signal myself.

Am open to a pull request.

**Comment by rix1337** [comment]
https://github.com/rix1337/RSScrawler/discussions/457
