### ISSUE TITLE
[Ombi] - Fehler beim Abruf der IMDb

### ISSUE THREAD

**Issue by postboy99** [rix1337/RSScrawler#466]
Hallo, 

Ich nutze OmbiV4 und latest docker image vom RSScrawler und habe folgende Fehlermeldung:

[Ombi] - Fehler beim Abruf der IMDb für: tt10383456

Dieser request konnte nicht verarbeitet werden. 
Ich vermute es hängt mit Sonderzeichen im Namen zusammen.

**Comment by rix1337** [comment]
## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

- **Genutzte Version** (kein Support für alte Releases)

- **Wird Python 3.9 oder aktueller genutzt?**
