### ISSUE TITLE
[Ombi] - Fehler beim Abruf der IMDb

### ISSUE THREAD

**Issue by postboy99** [rix1337/RSScrawler#467]
# [RSScrawler] Fehlermeldung

_**[Ombi] - Fehler beim Abruf der IMDb für: tt10383456**_

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
_**[Ombi] - Fehler beim Abruf der IMDb für: tt10383456 (DEBUG aktiviert)**_

- **Genutzte Version** (kein Support für alte Releases)
_**v.8.4.2**_
- **Wird Python 3.9 oder aktueller genutzt?**
_**Ich benutze Docker unter UNRAID, wie finde ich das heraus?**_

## Fehlerbeschreibung

_**Nachdem Hinzufügen der Serie "Charité" in OmbiV4, kommt oben genannte Fehlermeldung.**_

**Comment by rix1337** [comment]
Danke für das detaillierte Issue. Die betroffene IMDb ID hat sich geändert, sodass die Episodendaten nicht korrekt geladen werden konnten. Der IMDb-Abruf ist ab sofort stabiler.
