### ISSUE TITLE
Suche crawlt nur letzte Folge der Staffel

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/RSScrawler#469]
# [RSScrawler] Fehlermeldung
## Zwingend erforderlich
- docker wird verwendet
- DEBUG Log leider keine Infos

## Fehlerbeschreibung

Wird eine Serie aktiv über die eingebettete Suche angestoßen
und das Ergebnis umfasst die vollständige SJ serie und dieses wird ausgewählt.
So wird im folgenden immer nur die neuste Folge der Staffel nicht jedoch die ganze Serie
oder gar die gesamte Staffel gecrawlt.

**Comment by rix1337** [comment]
Das ist leider zu unspezifisch. Lade bitte deine (teilanonymisierte) RSScrawler.ini hoch und nenn den Namen der Serie(n) bei denen es klemmt.

**Comment by 9Mad-Max5** [comment]
Habe die ini als txt hochgeladen anders wollte is git nicht als ini.
[RSScrawler - upload.txt](https://github.com/rix1337/RSScrawler/files/5878895/RSScrawler.-.upload.txt)

Eine serie wäre etwa The last man on Earth.

Mir ist eben aufgefallen das Staffelpacks normal über click'n'load auch immer als einzelne folgen von SJ hinzugefügt werden.
Könnte sein das hierin auch schon das Problem liegt.

**Comment by rix1337** [comment]
Gutes Issue, Danke. 
Das von dir beschriebene Problem lag daran, dass Staffelpakete in der neuen SJ-API nicht sortiert bereitgestellt werden, sondern irgendwo. Dadurch wurden statt der Pakete einzelne Episoden priorisiert.

Habe dadurch einen zweiten Bug gefunden und gefixt:
Bei einzelnen Episoden konnte immer nur die zuletzt gefundene hinzugefügt werden.
