### ISSUE TITLE
Konnte Hostnamen nicht abrufen

### ISSUE THREAD

**Issue by DKeppi** [rix1337/RSScrawler#478]
Seit dem letzten Update kommt "Konnte Hostnamen nicht abrufen" und die Bereiche zum Aufklappen mit den Hostern haben keinen Text mehr!

Fehler aus Log:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rsscrawler/crawler.py", line 118, in crawler
    scraper = check_url(configfile, dbfile)
  File "/usr/lib/python3.6/site-packages/rsscrawler/url.py", line 37, in check_url
    ww_url = 'https://' + ww
TypeError: must be str, not bool
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rsscrawler/crawler.py", line 118, in crawler
    scraper = check_url(configfile, dbfile)
  File "/usr/lib/python3.6/site-packages/rsscrawler/url.py", line 37, in check_url
    ww_url = 'https://' + ww
TypeError: must be str, not bool

Version: 8.6.4

Im RSSCrawler.ini steht nur sf
Konfig wurde seit Ewigkeiten nicht verändert

![image](https://user-images.githubusercontent.com/2063381/108315118-3eb7fb80-71bb-11eb-8a67-07edda073a12.png)
![image](https://user-images.githubusercontent.com/2063381/108315158-4d9eae00-71bb-11eb-9bd2-c075053f8e04.png)

**Comment by rix1337** [comment]
Danke für das Issue. Ließ sich recht schnell beheben.
War ein guter Denkanstoß um das Webinterface so zu überarbeiten, dass es auch bei nur einem / wenigen gesetzten Hostnamen übersichtlich ist.

**Comment by DKeppi** [comment]
Sehr gerne! Ja allerdings, du warst flott ;)
Finde ich eine gute Verbesserung, nur die aktivierten zu sehen...

**Comment by rix1337** [comment]
Jo, wenn man immer mehrere Hostnamen nutzt fällt sowas nicht auf, aber durch das Issue war es offensichtlich.
Viel Spaß weiterhin mit dem RSScrawler
