### ISSUE TITLE
Bestimmter Film von Ombi führt zum Crash

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/RSScrawler#480]
# [RSScrawler] Fehlermeldung

## Zwingend erforderlich

- **DEBUG:rsscrawler:--------Alle Suchfunktion gestartet.--------
Erfolgreich mit Ombi verbunden.
DEBUG:rsscrawler:Erfolgreich mit Ombi verbunden.
Erfolgreich mit Ombi verbunden.
Die sichere Verbindung zu MyJDownloader konnte nicht verifiziert werden.
Bester Treffer fuer die Suche nach Pinocchio 2019 ist Pinocchio.2019.German.1080p.BluRay.x264-Tscc (BY)
Film: Pinocchio 2019 durch Ombi hinzugefügt.
DEBUG:rsscrawler:Bester Treffer fuer die Suche nach Pinocchio 2019 ist Pinocchio.2019.German.1080p.BluRay.x264-Tscc (BY)
Fehler beim Abruf von: //byte.to/topcover/top.php Invalid URL '//byte.to/topcover/top.php': No schema supplied. Perhaps you meant http:////byte.to/topcover/top.php?
--------Alle Suchfunktion gestartet.--------
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/rsscrawler/crawler.py", line 126, in crawler
    ombi_results = ombi(configfile, dbfile, device, log_debug, ombi_first_launch)
  File "/usr/lib/python3.6/site-packages/rsscrawler/ombi.py", line 143, in ombi
    rsscrawler.search.shared.content_all.download(best_result, device, configfile, dbfile)
  File "/usr/lib/python3.6/site-packages/rsscrawler/search/shared/content_all.py", line 121, in download
    url_hosters.append([link["href"], link.text.replace(" ", "")])
TypeError: 'NoneType' object is not subscriptable**

- **8.6.2-8.6.5**

- **Docker Container**

## Fehlerbeschreibung

Wird über Ombi (ja ich weiß, dass du es nicht magst..) der oben genannte Film hinzugefügt crasht der crawler.
Dabei kommt es zu folgender Fehlermeldung.
Anschließend startet er den Prozess von vorne.
Erst mit Löschen des Films aus den Ombi request läuft es wieder rund.

**Comment by 9Mad-Max5** [comment]
Scheint auch ein bug in der Websearch zu sein.
Ähnliches Fehlerbild beim versuch einen DL zu starten.
Auch hier wird über den Mangel der scraper variable gestolpert.

**Comment by rix1337** [comment]
dann schick mir bitte per Gitter-PM deine RSScrawler.ini
