### ISSUE TITLE
Paketname aufgrund "%20" nicht als hinzugefügt erkannt

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#498]
# [RSScrawler] Fehlermeldung
## Zwingend erforderlich

- **Genutzte Version** (kein Support für alte Releases)
9.2.1

- **Wird Python 3.9 oder aktueller genutzt?**
Docker

## Fehlerbeschreibung

Nachdem 9.2.1 per automatischem Suchlauf ein paar Releases auf DW gefunden hat, würden diese an den Helper übergeben und dort erfolgreich gelöst. Zurück kamen sie aber mit einem "%20" am Ende, so dass sie nicht dem Quellpaket zugeordnet wurden. Die Quellpakete blieben daraufhin als "C'n'L notwendig" stehen und lassen sich auch via "Paket löschen" nicht entfernen (es passiert schlicht nichts). Daraufhin habe ich den Container neu gestartet. Ein Suchlauf war zu dem Zeitpunkt nicht mehr aktiv. Nun scheint die Datenbank gesperrt zu sein.

**Comment by jankete** [comment]
Auch nach einem Neustart des Containers bleibt die Datenbank gesperrt.

`Drücke [Strg] + [C] zum Beenden
,Traceback (most recent call last):
,  File "/usr/lib/python3.6/site-packages/rsscrawler/crawler.py", line 359, in crawldog
,    db.reset()
,  File "/usr/lib/python3.6/site-packages/rsscrawler/db.py", line 78, in reset
,    self._conn.execute("DROP TABLE IF EXISTS %s" % self._table)
,sqlite3.OperationalError: database is locked
,Erfolgreich mit Ombi verbunden.
`

**Comment by rix1337** [comment]
Was sagt denn:
`fuser RSScrawler.db`

**Comment by rix1337** [comment]
Also halt den Container mal an, dann darf der Befehl keinen Prozess mehr zeigen.

**Comment by jankete** [comment]
Im Container sagt fuser:
`227 228`

Wenn ich ihn stoppe, kann ich ja aber keine Befehle mehr in ihm ausführen.

**Comment by rix1337** [comment]
Mach den Befehl mal mit gestopptem Container vom Docker host aus.

**Comment by rix1337** [comment]
Ich hab diese Issue mal umbenannt und aufgeräumt - Database is locked bitte unter #499 kommentieren

Dieses Issue löst ein gleich erfolgtes Update von Click'n'Load2RSScrawler

**Comment by rix1337** [comment]
`%20` wird ab sofort durch Click'n'Load2RSScrawler aus dem Paketnamen entfernt
Bitte auf das neue Image des Sponsors Helpers updaten. Im Startlog steht dort ab sofort auch die Version von Click'n'Load2RSScrawler

![grafik](https://user-images.githubusercontent.com/9930448/112690884-cceb6580-8e7c-11eb-82b7-698ce2e91779.png)

**Comment by rix1337** [comment]
@jankete bitte mit rc2 testen
[rsscrawler-9.2.2rc2-py3-none-any.zip](https://github.com/rix1337/RSScrawler/files/6214418/rsscrawler-9.2.2rc2-py3-none-any.zip)

**Comment by jankete** [comment]
Mit dem 9.2.2.-rc2 erscheint kein "%20" mehr 👍🏻
