### ISSUE TITLE
Database is locked

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#499]
# [RSScrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
Exception on /api/start_now/ POST
`
Exception on /api/start_now/ [POST]
,Traceback (most recent call last):
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
,    response = self.full_dispatch_request()
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
,    rv = self.handle_user_exception(e)
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
,    reraise(exc_type, exc_value, tb)
,  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
,    raise value
,    rv = self.dispatch_request()
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
,  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 104, in decorated
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
,    return self.view_functions[rule.endpoint](**req.view_args)
,    return f(*args, **kwargs)
,  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 604, in start_now
,    if not RssDb(dbfile, 'crawltimes').retrieve("startnow"):
,  File "/usr/lib/python3.6/site-packages/rsscrawler/db.py", line 19, in __init__
,    "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = '%s';" % self._table).fetchall():
,sqlite3.OperationalError: database is locked
`
Wenn ich die letzte Zeile sehe, könnte es also auch mit dem anderen Issue zu tun haben.

 - Weitere Exception:
`
Process Process-3:
,Traceback (most recent call last):
,  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
,    self.run()
,  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
,    self._target(*self._args, **self._kwargs)
,  File "/usr/lib/python3.6/site-packages/rsscrawler/crawler.py", line 211, in crawldog
,    db = RssDb(dbfile, 'crawldog')
,  File "/usr/lib/python3.6/site-packages/rsscrawler/db.py", line 20, in __init__
,    self._conn.execute("CREATE TABLE %s (key, value)" % self._table)
,sqlite3.OperationalError: database is locked
`

- **Genutzte Version** (kein Support für alte Releases)
9.2.1

- **Wird Python 3.9 oder aktueller genutzt?**
Docker

## Fehlerbeschreibung

Beim Klick auf "Suchlauf jetzt starten" erscheint erst "Suchlauf wird gestartet" und wenig später "Konnte Suchlauf nicht starten". Im Log findet sich dann o.g. Meldung. Der Suchlauf wird im Hintergrund aber wohl trotzdem gestartet, denn der Laufzeit Zähler nimmt die Arbeit auf.

**Comment by rix1337** [comment]
Was steht denn in der Exception?

**Comment by jankete** [comment]
`
Exception on /api/start_now/ [POST]
,Traceback (most recent call last):
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
,    response = self.full_dispatch_request()
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
,    rv = self.handle_user_exception(e)
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
,    reraise(exc_type, exc_value, tb)
,  File "/usr/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
,    raise value
,    rv = self.dispatch_request()
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
,  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 104, in decorated
,  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
,    return self.view_functions[rule.endpoint](**req.view_args)
,    return f(*args, **kwargs)
,  File "/usr/lib/python3.6/site-packages/rsscrawler/web.py", line 604, in start_now
,    if not RssDb(dbfile, 'crawltimes').retrieve("startnow"):
,  File "/usr/lib/python3.6/site-packages/rsscrawler/db.py", line 19, in __init__
,    "SELECT sql FROM sqlite_master WHERE type = 'table' AND name = '%s';" % self._table).fetchall():
,sqlite3.OperationalError: database is locked
`
Wenn ich die letzte Zeile sehe, könnte es also auch mit dem anderen Issue zu tun haben.

**Comment by rix1337** [comment]
Eine gelockte DB liegt vermutlich an etwas anderem - einfach mal den Container durchstarten, dann sollte es wieder gehen.

Ich werde aber die betroffene Funktion härten (try / except)

**Comment by jankete** [comment]
Neustart hilft leider nicht. Siehe auch https://github.com/rix1337/RSScrawler/issues/498#issuecomment-808491447

**Comment by jankete** [comment]
Docker Host ist eine Synology. Leider kennt deren Shell kein "fuser"

**Comment by rix1337** [comment]
Entpack bitte das angehängte ZIP und installier die enthaltenne whl Datei per PIP install im Container
Dann einmal neustarten
[rsscrawler-9.2.2rc1-py3-none-any.zip](https://github.com/rix1337/RSScrawler/files/6214324/rsscrawler-9.2.2rc1-py3-none-any.zip)

**Comment by jankete** [comment]
Hab's gelöst. Habe bei gestopptem Container die DB einfach unter neuem Namen kopiert, die alte .db gelöscht, der Kopie wieder den original Namen verpasst und dann den Container wieder gestartet. Auf die Art wurden alle eventuellen Filehandels von außen gekillt.

Soll ich die ZIP Geschichte trotzdem noch testen?

**Comment by rix1337** [comment]
Prima, dann hat 9.2.2 keine riesige Eile. Probier bitte trotzdem ob mit dem RC1 bei dir alles klappt, dann Release ich die.

**Comment by jankete** [comment]
Hab die 9.2.2 RC1 installiert und werde beobachten.

**Comment by rix1337** [comment]
Wenn auch bei ein paar Neustarts keine Probleme (mehr) auftreten, release ich. Sag bitte nochmal Bescheid was nach 2-3 Neustarts mit dem RC2 passiert.

**Comment by jankete** [comment]
Grundsätzlich hat die rc2 mit Neustarts kein Problem. Bleibt nur noch das Thema mit meinen "Paketleichen" (siehe Chat). Das ist aber eine andere Geschichte.

**Comment by rix1337** [comment]
Prima, damit ist alles erledigt.
