### ISSUE TITLE
Abschnitt "My JDownloader" lässt sich nicht mehr aufklappen

### ISSUE THREAD

**Issue by jankete** [rix1337/RSScrawler#506]
# [RSScrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
Leider kein Eintrag

- **Genutzte Version** (kein Support für alte Releases)
9.2.7

- **Wird Python 3.9 oder aktueller genutzt?**
Docker

## Fehlerbeschreibung

Ich starte den Crawler mit eingeklapptem "My JDownloader" Bereich. Dieser lässt sich seit dem neusten Update auf 9.2.7 nicht mehr ausklappen, wenn er angeklickt wird. Browser Cache habe ich schon geleert und das Problem tritt sowohl am Handy, als auch am PC auf (jeweils Chrome & Firefox).

**Comment by rix1337** [comment]
Danke für die Meldung - liegt an den aktualisierten Frameworks.

Da der RSScrawler den MyJDownlaoder Tab automatisch öffnet, wenn Pakete vorhanden sind und ihn schließt, sofern keine da sind, ist die Funktion nicht beeinträchtigt.

Ist kosmetisch und hat damit keine hohe Prio.

**Comment by jankete** [comment]
Völlig korrekt, die Prio ist gering. Aktuell fehlt mir so nur die Möglichkeit den JDownloader via "Schraubenschlüssel" zu aktualisieren, wenn gerade keine Pakete da sind. Aber dafür gibt es ja auch noch andere Wege.

**Comment by rix1337** [comment]
Ist erledigt. Frühere Bootstrap-Versionen haben offenbar ignoriert, dass der Tab auf die falsche ID eingerichtet war.
