### ISSUE TITLE
Recaptcha v2 Probleme (SJ Links offline)

### ISSUE THREAD

**Issue by Slomo17** [rix1337/RSScrawler#68]
Hi

Ich habe mit der neusten Version deines Scripts das Problem, dass Jdownloader die gefunden Folgen von SJ als offline anzeigt. Wenn ich sie mauell hinzufüge gehen sie problemlos. 
Ich kann leider nicht genau sagen, ob es ein Problem vom Script oder von Jdownloader ist.
So sieht das ganze aus (oben die über das Script gefundenen folgen, unten die manuell hinzugefügte):
![selection_001](https://cloud.githubusercontent.com/assets/14056946/16004605/cd6f7d92-3162-11e6-84e3-a0db9257ba85.png)

**Comment by rix1337** [comment]
Das hat nichts mit RSScrawler zu tun. JDownloader kann aktuell nicht richtig mit Recaptchas umgehen (siehe: https://svn.jdownloader.org/issues/79173 oder https://board.jdownloader.org/showthread.php?t=69422)

Es ist mittlerweile möglich seinen Google Account im JDownloader zu hinterlegen, sowie die Captchas ohne separates Browserfenster zu lösen, dazu aber mehr im JDownloader-Forum.

Hier kann ich am besagten Problem nichts lösen (wie auch in der Releasebeschreibung zu lesen).

**Comment by rix1337** [comment]
Ich lass diese Issue offen, um feedback/updates zu Recaptcha-Problemen zu sammeln.

Wenn schon JDownloader so erhebliche Probleme hat, bin ich froh nicht mehr auf Pyload zu setzen..

**Comment by Slomo17** [comment]
Oh ok,  sry, da hätte ich wohl genauer lesen sollen vorher. dann war es wohl zeitlich einfach zufalle, das ich gerade da auf das neue script upgedatet habe.

**Comment by rix1337** [comment]
Alles gut! Wenn Ich das Script zu Tode gepatcht habe helfen solche Issues wirklich.
In diesem Fall liegt es aber tatsächlich am JDownloader..

**Comment by neutron666** [comment]
Also aktuell arbeiten die JD Jungs daran. Das letzte Update hat PhantomJS integriert, ein headless browser, somit gehen aktuell schon mal die captcha's wieder manuell zu lösen, vorrausgesetzt man hat ein System wo PhantomJS installiert ist. Auf diversen Kisten wie z.B. dem Synology NAS mit unterschiedlichen CPU-Architekturen wird es die Tage auch Updates geben wo ein jeweiliges PhantomJS Binary compiliert herunter geladen werden kann. Das 9kw aktuell noch nicht will liegt wiederum daran das PhantomJS die Bilder teils zu groß an 9kw schickt, das wird aber ebenfalls durch die JD jungs angepasst, somit ist die volle Automatisierung dann auch wieder vorhanden.

**Comment by Slomo17** [comment]
Super das kling gut. Aber die neuen SJ captachs gingen doch mal mit 9kw, zumindest hat das bis vor einiger zeit bei mir geklappt. Das war der grund warum ich von pyload zu jdwonloader gewechselt bin. Gabs da wieder eine änderung?

**Comment by rix1337** [comment]
Joplin, es gab Änderungen die mittlerweile gefixt sind (gerade getestet ). Hinterlegt einen aktiven Google Account und 9kw.eu sollte wieder laufen.

**Comment by neutron666** [comment]
Ich muss leider warten bis das mit dem phantomjs geklärt ist. Ich nutze 2 factor authentication bei google und das mag der jd irgendwie nicht, zumindest kann ich den account nicht hinzufügen.

**Comment by rix1337** [comment]
2fa ging bei mir problemlos..komisch

Jedenfalls wird recapacha auf absehbare zeit ein Hindernis bleiben. Aber für jd2 ein bezwingbares.

**Comment by neutron666** [comment]
Wie haste das gemacht ? Bei mir will er danach einen Verification Code, oben steht aber Number: null

**Comment by neutron666** [comment]
Ich ziehe die Frage zurück, wenn man nicht nachdenkt...einfach mal den Google Authenticator nehmen und den verification code eintippen :P

**Comment by rix1337** [comment]
Ich sehe ihr habt das Problem gelöst..

**Comment by Slomo17** [comment]
Ja habs jetzt auch hin bekommen, Danke für die Hilfe
