### ISSUE TITLE
SerienJ

### ISSUE THREAD

**Issue by Gutz-Pilz** [rix1337/RSScrawler#69]
Hallo,

kann es sein, dass Jdownloader aktuell die Captchas nicht gelöst bekommt ?
benutze 9kw und es wird nichts gelöst...
Vorher ging alles wunderbar

Danke

**Comment by rix1337** [comment]
https://github.com/rix1337/RSScrawler/issues/68

Ich öffne mal die andere Issue, damit das nicht übersehen wird.

Kurz: Liegt an Recaptcha v.2 und dem JDownloader..
