### ISSUE TITLE
[Mac OS] Module werden nicht gefunden

### ISSUE THREAD

**Issue by badrabbit** [rix1337/RSScrawler#70]
Ich versuche das ganze unter Mac OS 10.11.6 El Capitan zum Laufen zu bringen. Bisher leider ohne Erfolg.

* ZIP von Github heruntergeladen, entpackt und im Userordner abgelegt
* Python 2.7 ist installiert
* Zusätzliche Module wurden ebenfalls installiert `pip install docopt`, `pip install lxml`, usw.

Beim Ausführen der Datei im Terminal erhalte ich folgende Fehlermeldung:

```
macmini-home-3:~ macmini_home$ python /Users/macmini_home/RSSCrawler/RSScrawler.py
Traceback (most recent call last):
  File "/Users/macmini_home/RSSCrawler/RSScrawler.py", line 35, in <module>
    from docopt import docopt
ImportError: No module named docopt
```

docopt ist aber bereits installiert:

```
macmini-home-3:~ macmini_home$ pip install docopt
Requirement already satisfied (use --upgrade to upgrade): docopt in /usr/local/lib/python2.7/site-packages
```

Was mache ich hier falsch bzw. wo sucht RSScrawler nach den Modulen?

**Comment by rix1337** [comment]
Ich kenne mich mit Mac OS nicht aus.

Der Fehler liegt aber daran, dass python das Modul nicht findet. Ich recherchieren, wie man docopt (evtl ohne pip) installiert.

**Comment by badrabbit** [comment]
Für alle, die auf die gleichen Probleme bei der Installation unter Mac OS X / macOS stoßen, hier die Lösung:

Die fehlenden Module müssen mit:

`python -m pip install [MODULNAME]`

installiert werden.


Danach werden sie auch korrekt gefunden!

**Comment by rix1337** [comment]
Danke für den Hinweis. Steht ab sofort im Readme.
