### ISSUE TITLE
Diskstation DSM 6.0 lxml

### ISSUE THREAD

**Issue by lennnox1** [rix1337/RSScrawler#71]
Ich habe ein Problem, wenn ich lxml installieren will. Ich bekomme immer die Fehlermeldung:

" Setup script exited with error: command '/usr/local/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-ccache-gcc' failed with exit status 1"

Wenn ich "gcc -v" eingebe -> gcc version 5.3.0 (GCC)

Vielen Dank schonmal für die Hilfe :)

**Comment by rix1337** [comment]
Ich biete keinen Synology build/support.

Frag am besten Neutron im Synology Forum... Wobei der build dort mittlerweile stark veraltet ist.
