### ISSUE TITLE
Qnap

### ISSUE THREAD

**Issue by Itsie** [rix1337/RSScrawler#79]
Hi,

gibt es die Möglichkeit das ganze auch via qNap zu nutzen, notfalls ohne Autosetup.

LG

**Comment by Itsie** [comment]
Würd dafür sogar spenden ;)

**Comment by rix1337** [comment]
**Ich nehme keine Spenden an.** Wer das Projekt im aktuellen Zustand mag und sich dafür bedanken möchte kann Bitcoin senden. Features und Support werden hier nicht verkauft.

Zum Thema:
Qnap scheint docker zu unterstützen:
https://www.qnap.com/de-de/tutorial/con_show.php?op=showone&cid=179

Setze also docker auf und lad dann das aktuelle:
https://hub.docker.com/r/rix1337/docker-rsscrawler/
Image.

/config muss dann auf dein NAS umgeleitet werden (enthält die Einstellungsdateien)
/jd2/folderwatch musst du auf das folderwatch Verzeichnis deines JDownloaders umleiten.

**Comment by Itsie** [comment]
Hi,

die Frage die sich stellt, wie ich das JD Verzeichnis angeben soll.
Geht es da wirklich nur um den Folderwatch Ordner? Oder benötigt dein Script wirklich Jdownloader für irgendwas anderes zusätzlich?

Sonst würde ich den /public folder nehmen und folderwatch sich daraus bedienen lassen.

LG

Von: RiX [mailto:notifications@github.com]
Gesendet: Montag, 5. September 2016 09:19
An: rix1337/RSScrawler <RSScrawler@noreply.github.com>
Cc: Sascha Vierke <sascha@4ke.me>; Author <author@noreply.github.com>
Betreff: Re: [rix1337/RSScrawler] Qnap (#79)


Ich nehme keine Spenden an. Wer das Projekt im aktuellen Zustand mag und sich dafür bedanken möchte kann Bitcoin senden. Features und Support werden hier nicht verkauft.

Zum Thema:
Qnap scheint docker zu unterstützen:
https://www.qnap.com/de-de/tutorial/con_show.php?op=showone&cid=179

Setze also docker auf und lad dann das aktuelle:
https://hub.docker.com/r/rix1337/docker-rsscrawler/
Image.

/config muss dann auf dein NAS umgeleitet werden (enthält die Einstellungsdateien)
/jd2/folderwatch musst du auf das folderwatch Verzeichnis deines JDownloaders umleiten.

**Comment by rix1337** [comment]
Der Docker Container verweist explizit auf /jd2 als JDownloader-Verzeichnis.
Du kannst selbst wählen wohin du diesen Pfad umleitest.
Von der Logik her muss /jd2 auf das Verzeichnis des Jdownloaders verweisen, das folderwatch enthält.

Du kannst aber natürlich auch gleich /jd2/folderwatch direkt auf dein folderwatch Verzeichnis (wo auch immer) umleiten.

Ich kenne die QNAP Struktur nicht, aber auf meinem Server leite ich einfach
/jd2/folderwatch auf /etc/jdownloader/folderwatch um.

Solange die crawljobs im richtigen Ordner ankommen ist alles ok.

**Comment by Itsie** [comment]
Aber es reicht nicht im Folderwatch (myJDownloader Webinterface) den Pfad zu ?ndern ? Die Docker Container sind alle in /share/volume/public/docker ich kann bei docker auch Volumes einh?ngen .. aber es w?re einfacher wenn ich dein Script das direkt in Public speichern lasse und JD Folderwatch den Ordner nutzen lasse. Ich wei? halt nicht wie ich die Struktur angehen soll bzw den Pfad wenn ich hier /share/volume/.qpkg/JDownloader nutzt er sicherlich den Container Pfad oder ? Kenne das so von KVM oder OpenVZ oder habe ich hier einen Denkfehler ????

Sorry das ich dich so bel?mmer ich will das einfach schaffen :) Hab schon echt ?berlegt ob ich auf die DS216+|| wechseln soll, da dein Script genau das abdeckt was ich mir je gew?nscht habe.


Alternativ w?re evtl die Option einen lxc Container mit Debian anzulegen und da beides zu nutzen also JD und dein Script. Basiert ja eig auf Python und sollte ja von ?berall ausf?hrbar sein oder ?


LG


Am 07.09.2016 um 11:05 schrieb RiX <notifications@github.com<mailto:notifications@github.com>>:


Der Docker Container verweist explizit auf /jd2 als JDownloader-Verzeichnis.
Du kannst selbst w?hlen wohin du diesen Pfad umleitest.
Von der Logik her muss /jd2 auf das Verzeichnis des Jdownloaders verweisen, das folderwatch enth?lt.

Du kannst aber nat?rlich auch gleich /jd2/folderwatch direkt auf dein folderwatch Verzeichnis (wo auch immer) umleiten.

Ich kenne die QNAP Struktur nicht, aber auf meinem Server leite ich einfach
/jd2/folderwatch auf /etc/jdownloader/folderwatch um.

Solange die crawljobs im richtigen Ordner ankommen ist alles ok.

-

**Comment by rix1337** [comment]
Folgendes: Docker Container sind eine Art abgeschlossener Bereich. Zeit das zu erklären hab ich kein, daher nur kurz: Du musst dem Docker Container Sagen (wo auch immer du den Container "verwaltest", also startest) dass er einen Pfad aus sich heraus an das Dateisystem weiterreichen soll. Ansonsten Läuft der Crawler und du erhälst keine Dateien.

Du solltest Zwingend den /config Pfad des Containers irgendwo ablegen bspw. auf /share/volume/RSScrawler
Sonst kannst du keinerlei Einstellungen bearbeiten.
Wenn du den /jd2/folderwatch Pfad aus dem Container bsp. auf /share/volume/folderwatch umleitest und deinem JDownloader per Webinterface erklärst, dass er von dort aus importieren soll dürfte alles laufen.

Ohne die Umleitungen von /config und /jd2/folderwatch bringt dir der Container nichts.

Docker erleichtert aber die Einrichtung extrem. Alternativ kannst du versuchen:
python und alle Pakete der requirements.txt manuell zu installieren und irgendwie den RSScrawler auf deinem QNAP abzulegen & zu starten. Das wird aber sicher mühsamer als Docker zu nutzen.

**Comment by Itsie** [comment]
Hi,

ich glaube das hat sich gerade erledigt:
Screenshot vom Docker Container von dir :+1: 
![Image of QNAP](http://4ke.me/15CJM)

Screenshot vom JD Docker Container von docker-jdownloader2-1:
![Image of QNAP](http://4ke.me/YjP1)

Scheinbar ist es so einfach, dass ich es selber nicht glauben mochte ;).

Würde ja bedeuten ich müsste einfach nur in deiner config den Pfad auf:
/jd2/folderwatch 

setzen oder muss es /jd2/ sein?


Danke dir hierfür, die Spende geht in diesem Moment auch auf den Weg.

**Comment by rix1337** [comment]
Die Screenshots kann ich leider nicht sehen :-1: 

Ich würde die Pfade /config und /jd2/folderwatch auch auf deinem System trennen, das könnte Probleme verursachen.

Wenn du auf deinem QNAP die RSScrawler-Dateien sehen kannst, dort ein "Einstellungen"-Ordner auftaucht und nach dem Befüllen der Listen dein JDownloader sachen runterläd hat alles geklappt.

**Comment by Itsie** [comment]
Hi,

musst du einmal aktualisieren, dann siehst du was ;).
Hatte den falschen Pfad genutzt zu den Bildern.

Die Pfade sind getrennt oder irre ich, siehst du leider erst auf den Screens.

Von: RiX [mailto:notifications@github.com]
Gesendet: Mittwoch, 7. September 2016 11:44
An: rix1337/RSScrawler <RSScrawler@noreply.github.com>
Cc: Sascha Vierke <sascha@4ke.me>; Author <author@noreply.github.com>
Betreff: Re: [rix1337/RSScrawler] Qnap (#79)


Die Screenshots kann ich leider nicht sehen 👎

Ich würde die Pfade /config und /jd2/folderwatch auch auf deinem System trennen, das könnte Probleme verursachen.

Wenn du auf deinem QNAP die RSScrawler-Dateien sehen kannst, dort ein "Einstellungen"-Ordner auftaucht und nach dem Befüllen der Listen dein JDownloader sachen runterläd hat alles geklappt.

**Comment by rix1337** [comment]
Lad die Bilder mal auf suckmypic oder imgur hoch. Auf https://github.com/rix1337/RSScrawler/issues/79 sind die nicht sichtbar.

**Comment by Itsie** [comment]
Hi,

erneut:

Dein Container (Docker):
https://suckmypic.net/byjoVw3k.png

Jdownloader (Docker): 
https://suckmypic.net/NkvpGots.png

Nebenbei: An den Einstellungsordner komme ich via WinSCP oder Shell, das ist folglich kein Problem.

**Comment by rix1337** [comment]
Dann nur folgendes. Zum JDownloader Container kann ich nichts sagen, aber:
Die Screenshots sehen gleich aus.
Den Einstellungsordner braucht nur RSScrawler, jdownloader braucht nur Zugriff auf den folderwatch Ordner.

So wie es jetzt aussieht sollte dein Setup aber funktionieren. Du musst nur dem JDownloader sagen, dass er seine crawljobs aus /jd2/folderwatch beziehen soll.

**Comment by rix1337** [comment]
https://suckmypic.net/8tOeO439.png

Stell das so ein. JD2 braucht den /config Pfad nicht durchreichen, der existiert im JD2 Container evtl. gar nicht!

Dann musst du für den Crawler nur (Ob WinSCP oder mit anderen Tools) die Einstellungen anpassen.

JDownloader muss dann nach /pub herunterladen
und seine Ordnerüberwachung auf /jd2/folderwatch richten

**Comment by Itsie** [comment]
Hi,

wird heute Abend getestet wenn ich von der Arbeit komme, sollte aber ja soweit gehen ;). 
Nun wollen wir hoffen das in dem Docker Container phantomJS installiert ist für recaptcha und ich bin ein glücklicher Mensch !!

Hast du evtl. Paypal oder kannst mir ne schnelle Möglichkeit nennen, Bitcoins zu kaufen und dir zukommen zu lassen? Ich finde die Arbeit die du dir gemacht hast Spitze und möchte mich natürlich auch bedanken.

**Comment by rix1337** [comment]
Viel Spaß damit,

die Programmierung war grundsätzlich ein Hobbyprojekt. Nur den ersten Code musste ich von einem Freelancer machen lassen, was teuer war.

https://anycoindirect.eu/de/kaufen/bitcoins sollte funktionieren

**Comment by Itsie** [comment]
Hallo Rix,

hier nochmal mein Feedback:
Es funktioniert solala , die JD Instanz aus Docker haut ordentlich auf den Ram.
Naja wie es scheint muss ich doch wohl die 216+ II ordern und irgendwie schauen ob ich da PhantomJS zum laufen bekomme, optional versuche ich mal docker @ Windows , evtl. mache ich es einfach von hier. Vorbei der Traum vom automatisierten Downloaden ;). 

Wie regelst du das denn? Läuft Serienjunkies bei dir? Es nutzen scheinbar soviele dein Script, es muss doch einen Haken geben, irgendwie muss da doch was laufen.

LG

**Comment by Itsie** [comment]
BTW: Spende sollte unterwegs sein, laut anycoin dauert dies 1-2 Tage.

**Comment by rix1337** [comment]
Das Programm ist ja in Python geschrieben und funktioniert deswegen überall wo Python läuft. Dein Limit ist eher der JDownloader. Ich habe einen Heimserver auf Linuxbasis, der sehr gut läuft. Wenn du Programme auf deinem NAS laufen lassen willst nimm am besten eins mit potentem Prozessor.. Auf dem DS216+II läuft vielleicht sogar ein Medienserver wie Plex.

Ansonsten empfehle ich einfach einen kleinen HTPC/Server selbst zu bauen. Der kann dann mit Windows/Linux etc. laufen. 

Ein kostenloses NAS-Betriebssystem wäre Openmediavault.
Ich empfehle definitiv UNRAID von Lime-Technology. Das schützt deine Daten, unterstützt Docker, eigengene Plugins (Programme) und VMs. Im Prinzip kannst du auf deinem NAS einen Virtuellen Gaming-PC laufen lassen, oder gleich 7: https://www.youtube.com/watch?v=LXOaCkbt4lI

**Comment by Itsie** [comment]
Hi,

Plex läuft jetzt auch wunderbar, dass QNAP Nas hat sogar einen nen celeron Quadcore cpu.
Ich versuche mich nun an einer VM mit Debian und beiden Optionen ;)
Unraid sieht sehr gut aus, danke schonmal hierfür, über ein HTPC habe ich desöfteren auch schon nachgedacht.

Danke dir !

**Comment by rix1337** [comment]
Die Bitcoin sind angekommen. Danke dafür

**Comment by Itsie** [comment]
Hallo Rix, 

dafür doch nicht ;) Sag mal wie kann ich einen Python Prozess automatisiert laufen lassen? Mit Screen oder gibt es da eine andere Möglichkeit?

**Comment by rix1337** [comment]
Das hängt von deinem System ab und es gibt zig Wege das zu bewerkstelligen. Ich würde es wie folgt versuchen:

Bearbeite ```/etc/rc.local```

Schreib dort vor ```exit 0```
```python /pfad/zu/RSScrawler/RSScrawler.py &```

Das sollte theoretisch den RSScrawler starten (dazu muss die Konfiguration stimmen, also wenn du das Script startest sollte es laufen, statt sich über fehlende Einstellungen etc. zu beklagen).

Das ```&``` ist wichtig, damit das rc.local Script nicht in einer Endlosschleife hängen bleibt. Also nicht vergessen.

Wenn das nicht funktioniert musst du wohl googlen.. Ist ein etwas unübersichtliches Thema. Vielleicht schreibts du dir auch ein init.d Service-Script..

**Comment by Itsie** [comment]
Hey Rix,

Hast du eine Ahnung warum z.B:
Quantico.*

Nur :
2016-09-21 07:49:15,191 - Quantico.S01E17.GERMAN.Dubbed.720p.WebHD.h264-idTV
2016-09-21 07:49:17,673 - Quantico.S01E18.GERMAN.Dubbed.720p.WebHD.h264-idTV

crawlt?

Im SJ RSS ist:
Quantico.S01E20-22.German.DD51.Synced.DL.720p.iTunesHD.AVC-TVS

Und in der SJ_Serien.txt hab ich folgendes probiert:
Quantico.*.German.DD51.Synced.DL.720p.iTunesHD.AVC-TVS
Quantico.*

Evtl. hier noch eine Idee?

**Comment by rix1337** [comment]
Ich habe mich mal auf die Fehlersuche begeben:

RSScrawler sucht im Feed von SJ nach Titeln, wenn du dir diesen anschaust siehst du, dass diese Titel nicht direkt auf einen Link verweisen, sondern auf eine Unterseite.
Das Script sucht also einen Titel (und findet hier auch den Quantico.S01E20-22-Eintrag), muss aber dann auf der Unterseite nach exakt diesem Titel suchen um Links zu finden.
Da die Episoden aber auf der Unterseite als Einzellinks und nicht als das 20-22-Paket auftauchen läuft RSScrawler ins leere.

Danke für die Fehlermeldung, ich überlege mir wie ich das beheben kann. Liegt aber Prinzipiell an SJ.


___

Nur der Vollständigkeit halber:
in SJ_Serien.txt musst du keine Sonderzeichen einfügen, da reicht der Serientitel mit Leerzeichen (ohne Umlaute), also bspw. Quantico

Wenn du Regex-Suchen laufen lassen willst nimm die SJ_Serien_Regex.txt und füge da bspw.
Quantico.*.DL.*.720p.*-(TVS|4SJ) als Regex-Eintrag ein.

**Comment by rix1337** [comment]
Update: ist behoben. Da war ein Tippfehler im Originalscript 👍
