### ISSUE TITLE
[RSScrawler] Dokujunkies Integration

### ISSUE THREAD

**Issue by badrabbit** [rix1337/RSScrawler#81]
Wäre eine Dokujunkies-Integration möglich? Soweit ich weiß, bieten die ja keinen RSS-Feed an.

**Comment by rix1337** [comment]
Dazu müsste jemand eine Suchfunktion für DJ/SJ schreiben.. ohne xml feed ist das extrem schwierig auszulesen.. Sorry, eher nicht. Ich lass das mal als Wunsch offen.
