### ISSUE TITLE
flexget implementation?

### ISSUE THREAD

**Issue by snickers2k** [rix1337/RSScrawler#82]
Hey. Gäbe es eine Möglichkeit deine search-Plugins auch mit flexget zu verwenden, statt mit einer .txt zu füttern? Die alten plugins von gutz-pilz, die ich bisher genutzt habe, funktionieren scheinbar nicht mehr.
Bisherige searches in flexget wurden so durchgeführt: "http://path/to/url/hd-area.php?var={{search_term}}".
Wäre dir sehr dankbar... 
Ps. Was war eigentlich dein Grund flexget den rücken zu kehren?

**Comment by rix1337** [comment]
Hi. Die Geschichte lief anders: 

Sonarr ist der beste Weg Serien automatisch zu beziehen.. nur eben nicht auf Deutsch. Dabei sucht das Programm eine Liste nach neuen Releases ab.

Pyload und dessen Plugins haben diese Lücke recht gut geschlossen, wobei Pyload im Grunde zwei Jahre lang vor sich hinvegitierte und letztlich Anfang dieses Jahres unbrauchbar wurde.

Also habe ich es kurzzeitig mit Flexget versucht. Flexget ist aber:

a) unnötig komplex

b) nicht einfach in der Lage eine vorhandene Liste abzusuchen

Daher habe ich Flexget so gut wie sofort wieder den Rücken gekehrt und gemeinsam mit einem Freelancer dieses Script entwickelt, dass die alten Pyload Scripte selbstständig laufen lässt und in den JDownloader integriert.

Da Flexget eben nicht einfach eine Liste an Titeln abarbeitet, sondern auf Basis bspw. einer IMDb Liste etc. die Automation genau anders herum (im Vergleich zu den Pyload Scripts) aufzieht werde ich das Programm nicht unterstützen.

**Comment by rix1337** [comment]
Ich zitiere die Readme:
```Um das Projekt zu erweitern muss entsprechender Code als Pull-Request eingereicht werden! Issues dienen nur der Fehlermeldung.```
