### ISSUE TITLE
closed ?!

### ISSUE THREAD

**Issue by snickers2k** [rix1337/RSScrawler#83]
Einfach schließen und trotz völliger Ahnungslosigkeit nicht mal auf ne Erklärung warten. Solche Leute liebe ich.
Natürlich kann man flexget mit einer simplen .txt füttern 
`include: series.yml ` in die config und die yml dann zB so aussehen lassen: https://github.com/erichlf/flexget/blob/master/series.yml

Aber da du ja alles besser weißt, mach mal weiter mit deinem "freelancer" (?) ;)

Ach und btw. eine simple flexget config erfordert evtl 20 zeilen copy&paste .. da ist nix unnötig kompliziert. Es gibt nur einfach viel Luft nach oben

**Comment by rix1337** [comment]
Mach dein eigenes Projekt auf, Arschloch :)
