### ISSUE TITLE
Der Webserver ist erreichbar unter...

### ISSUE THREAD

**Issue by Itsie** [rix1337/RSScrawler#88]
# [RSScrawler] Fehlermeldung
 print('Der Webserver ist erreichbar unter ' + socket.gethostbyname(socket.gethostname()) +':' + str(port) + '/' + prefix)

### Fehlerbeschreibung:
Nach Update von RSSCrawler bekomme ich das Script nicht mehr gestartet.

## Informationen:

-Betriebssystem
Debian 8.5 / Auf virtualisiertem Container einer QNAP Nas

-Version des RSScrawlers (mindestens 2.x.x)
v.2.0.5 
### Logauszug:

Die Logzeilen (DEBUG) zum Fehler:
root@flexget:~/RSScrawler# python RSScrawler.py
┌─────────────────────────────────────────────────────────┐
│ Programminfo:    RSScrawler v.2.0.5 von RiX             │
│ Projektseite:    https://github.com/rix1337/RSScrawler  │
└─────────────────────────────────────────────────────────┘
Nutze das "folderwatch" Unterverzeichnis von "/rss" für Crawljobs
Traceback (most recent call last):
  File "RSScrawler.py", line 1000, in <module>
    print('Der Webserver ist erreichbar unter ' + socket.gethostbyname(socket.gethostname()) +':' + str(port) + '/' + prefix)
socket.gaierror: [Errno -2] Name or service not known

LG Itsie ;).

**Comment by rix1337** [comment]
Schau ich mir morgen in ruhe an. Debian scheint die IP woanders im System zu hinterlegen.

Löschen ruhig erstmal die Zeile aus der RSScrawler.py dann sollte es laufen. 

Danke für die ausführliche Fehlermeldung!

Ps: cherrypy installieren nicht vergessen

**Comment by rix1337** [comment]
Versuch es mal erneut. Debian hinterlegt die IP-Adresse anders als Ubuntu und Windows, das hat für ein Problem gesorgt.

Ist aber nur eine Hilfsfunktion. Wenn es damit noch immer nicht geht entferne ich die Prüfung erstmal..

**Comment by rix1337** [comment]
Bis auf weiteres gelöst. Feedback erbeten :)

**Comment by Itsie** [comment]
Hi,

danke erstmal es scheint zu laufen, der Port läuft auf 9090 auch , laut netstat -tulpen.
Jedoch ist der Webserver nicht erreichbar? Ist es denn funktionierend? Bei mir ist sicherlich das Problem, dass ein natting genutzt wird. Muss schauen wie ich das behebe.

LG

**Comment by rix1337** [comment]
Hi,

klingt erstmal gut. Wenn du curl installiert hast, kannst du auf deinem Server mit

```curl localhost:9090``` prüfen, ob der Server läuft (sollte html-code ausspucken).

Du musst die Adresse aufrufen, die dir RSScrawler in der Konsole meldet.
Also bei vergebenem prefix = crawler wäre das auf meinem Server
172.17.13.73:9090/crawler

Wichtig ist: Wenn dir curl code anzeigt liegt dein Aufrufproblem an deiner Firewall bzw. NAT. Dann müsstest du dein RSScrawler-Port freigeben

**Comment by Itsie** [comment]
Hi,

geht nun, leider ist die Container Station von QNAP etwas dumm. Du kannst keine Ports freigeben wenn du Sie vorab nicht definiert hast (er tunnelt Sie nicht). Wie dem auch Sei, ein guter Tipp für deine Dokumentation bzw. für die Leute die es via Docker oder LXC auf QNAP / Synology versuchen, gebt vorher euren Wunschport frei, ich habe es nun mit dem Standaport versucht und es klappt.

Allerdings ist die Adresse nicht wie z.B angezeigt : 10.0.3.62:9090 sondern die vom NAS und zusätzlichem Port 9090. Ich danke dir mal wieder für die super Hilfe @rix1337  .

Ist es eig. auch möglich von Movieblog alles mit z.B:
German -PSO runterzuladen was in den RSS Feeds landet?

Immoment kriege ich bei allem was ich eintrage egal ob mit Placeholdern oder eine explizite Suche folgendes:
`Traceback (most recent call last):
  File "RSScrawler.py", line 1059, in <module>
    el.periodical_task()
  File "RSScrawler.py", line 193, in wrapper
    func(self)
  File "RSScrawler.py", line 436, in periodical_task
    for (key, value, pattern) in self.searchLinks(feedparser.parse(url)):
  File "RSScrawler.py", line 265, in searchLinks
    found = re.search(s,post.title.lower())
  File "/usr/lib/python2.7/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python2.7/re.py", line 244, in _compile
    raise error, v # invalid expression
` 
LG

**Comment by Itsie** [comment]
Ah ok, es kommt wegen dem Eintrag:
*.-PsO

Wie suche ich korrekt nach Filmen von der Releasegroup die im RSS Feed landen? 
Die Struktur variiert ja leider.

LG

**Comment by rix1337** [comment]
> Allerdings ist die Adresse nicht wie z.B angezeigt : 10.0.3.62:9090 sondern die vom NAS und zusätzlichem Port 9090. Ich danke dir mal wieder für die super Hilfe @rix1337 .

Das ist tatsächlich systembedingt so. Habe in Version 2.0.7 einen entsprechenden Hinweis eingebaut. Hatte mich aber hier mißverständlich ausgedrückt.

Danke @Itsie für die rasche und freundliche Fehlermeldung. Ist nicht oft so, dass man online einen ordentlichen Dialog führen kann.

> Ist es eig. auch möglich von Movieblog alles mit z.B:
> German -PSO runterzuladen was in den RSS Feeds landet?

[...]

> Wie suche ich korrekt nach Filmen von der Releasegroup die im RSS Feed landen? 
Die Struktur variiert ja leider.

Es gabe eine ähnliche Funktion mal im Originalscript. Dort konnte man gesondert nach
Titel, Auflösung, Group suchen.

War aber nicht so super ausgereift. Wenn du einen konkreten Wunsch hast (etwa wie bei SJ_regex) gibt es hiermit die offizielle Erlaubnis eine Issue mit Bitte um Erweiterung aufzumachen.

Für deine Zwecke sollte es aber reichen einfach nur

```PSO```

in die Filmliste einzutragen. Findet jedenfalls bei mir eine Menge aktueller Titel. Setz dann aber besser "Suchfunktion statt Feed nutzen:" auf False

Ansonsten lädt RSScrawler fleißig jedes Release von PSO runter. Jedes.

**Comment by Itsie** [comment]
Hi,

du ich finde wenn sich jemand die Mühe macht und dann noch zusätzlich in ein Script wie dieses zu investieren, der verdient es auch ordentliche Informationen zu erhalten, es bringt recht-herzlich wenig und kostet unnötig Zeit wenn du alles erfragen musst.

Scheinbar scheint in deinem "code" nicht der Eintrag vorhanden zu sein, den ich setzen soll ;).

Bezüglich des Issues, danke für deine Erlaubnis einen Issue zu erstellen.
Ich werde mir nachher die nötige Zeit nehmen und einen erstellen.

Ansonsten bitte ich alle die hier einfach nur lesen @rix1337  zu Unterstützen, ich werde dies auch demnächst erneut tun.

LG

**Comment by Itsie** [comment]
Ah sorry und eine Frage die ich vergessen habe, ist es evtl. möglich bei dem folgendem  Beispiel:
Serie.*.*.DL.*720p* eine Abfrage anzuführen, dass er nicht von unterschiedlichen Releasegroups läd?

Hintergrund:
Natürlich möchte man schnellstmöglich ans aktuelle Release gelangen, mir ist das egal von welcher Releasegroup, hauptsache die Qualität stimmt. Leider kommt es ab und zu vor, dass z.B an 2 verschiedenen Tagen unterschiedliche Releases rauskommen und die noch im RSS-Feed stehen.


PS: Hast du nochmal den Link für die Bitcoin Kauf option? ;)

**Comment by rix1337** [comment]
Ach Mist, der Kommentar unterstützt Markdown nicht richtig.

Du musst nur "Pso" in die Liste eintragen. Also nur die drei Buchstaben..Das sollte schon reichen.

Ich schau mir aber mal in den nächsten Tagen an ob ich die alte suche reaktiviert bekomme..

Ich hatte lange vor was an der ini zu machen und letztlich den Webserver für ein neues wording genutzt. Die besagte Option heißt in der ini "historical"

Die Idee mit dem Bash Script klingt gut, schieß ruhig los!

Und zu deiner SJ frage..Ich selbst mixe meine listen entsprechend. Releases egal welcher Group lass ich in der Serien Liste suchen. Spezielle anfragen laufen über regex.

Schau dir mal mein docker-verarbeitung an. Das sortiert alle Serien und Filme, remux sogar die zweisprachigen Releases in 1080p und ersetzt vorhandene Episoden durch neuere.

Alles automatisch, basiert auf filebot.

Wenn du magst, fügt deine Anfrage in der #73 hinzu. Habe irgendwann vor das für Filme umzusetzen.  Warum nicht auch für Serien?

Und zu guter letzt: anycoin.de

Kann alles etwas dauern. Die nächsten Wochen werden recht hart.

Mfg

**Comment by Itsie** [comment]
Hi,

ja nun passt alles ;). Mal sehen wie es läuft.
Filebot habe ich auch im Einsatz, aber nicht derart ausgereift, ich nutze es derzeit nur für Serien.
Was ich nicht wusste, dass Filebot auch Kategorisieren kann und unterschiedliche Ordnerstrukturen aufbauen kann. Es scheint aber zu funktionieren. Ich werde mal einen Docker-Container anlegen und das ganze testen. Wie es scheint, könnte ich das alles zusätzlich in das Shell Script packen.

Obwohl ich mittlerweile sagen muss, dass natürlich auch alles mit Docker möglich wäre, ich finde es nur sau umständlich bzw. ungewohnt.

Ja kein Stress wie gesagt, alles was gut ist brauch Weile ;).

LG

**Comment by Itsie** [comment]
Hey Rix,

schau mal was meinst:

` 
~Variables.
hinweis=' Bitte ändere den JDownloader Pfad in unter /Einstellungen/RSScrawler.ini oder im Webinterface'

~ Install Requirements RUN apt-get update
apt-get --yes --force-yes install git python2.7 python-setuptools python-pycurl python-beautifulsoup libxml2-dev libxslt-dev python-dev lib32z1-dev git
easy_install pip
pip install --upgrade pip virtualenv virtualenvwrapper
pip install docopt feedparser lxml requests cherrypy

~ get RSScrawler
git clone https://github.com/rix1337/RSScrawler.git
cd RSScrawler
mkdir /home/folderwatch/

~ Start RSSCrawler
python RSScrawler.py

~ Clear for a better overview
   clear

~ Ausgeben des Directorys
msg=`echo RSSCrawler Directory is \`pwd\``
echo $msg

~ Ausgeben des Hinweis für Änderung des JD Pfad´s
echo  $hinweis

~Erneutes Starten von RSSCrawler
python RSScrawler.py --jd-pfad=/home &
`

Ich suche derzeit noch der Möglichkeit eines Eingabepromts mit Möglichkeit via sed, den Port und den JD-Pfad einzugeben und ersetzen zu lassen, hast du evtl. eine Idee?

Ansonsten erweitere ich es noch um Filebot, aber dazu muss ich dazu kommen ;).
Die Darstellung ist extrem dumm hier auf GitHub, musste Raute durch ~ ersetzen. 


LG

**Comment by rix1337** [comment]
Sieht schon recht gut aus. Muss nur getestet werden.

Ich glaube es wäre gut den crawler irgendwo abzulegen bspw unter /user/bin o.Ä.

Den JDownloader Pfad im Script abzufragen ist eine gute Idee.

Ehrlich gesagt überlege ich für solche Infos die Wikifunktion von github zu nutzen!

**Comment by Itsie** [comment]
Hi,

keine schlechte Idee mit dem Wiki. 
Um flexibel zu bleiben dachte ich, ich gebe keinen Pfad vor. Aber auch das sollte mit einer Abfrage klappen, den Standard setze ich dann auf /home/user o.Ä , es klappt jedoch bisher wunderbar.

Wäre schön, wenn ein Wiki gepflegt werden könnte, gerade sowas schafft in einem Fall wie hier Übersicht. Ich bin aber noch am basteln, gib mir ein paar Tage ;).

LG

**Comment by Itsie** [comment]
Hi,

so probiere es selber auf Debian oder Ubuntu ;) , es klappt Wunderbar mit Port und Pfadwechsel.

```
#!/bin/bash
 
# Please take a look at: https://github.com/rix1337/RSScrawler/
# If you like RSSCrawler, say thank you : https://github.com/rix1337/thanks 

# Install Requirements  apt-get update
apt-get --yes --force-yes install git python2.7 python-setuptools python-pycurl python-beautifulsoup libxml2-dev libxslt-dev python-dev lib32z1-dev git
easy_install pip
pip install --upgrade pip virtualenv virtualenvwrapper
pip install docopt feedparser lxml requests cherrypy

# Clear for a better overview
   clear

# choose Path & Port
read -rp "Please enter the RSSCrawler setup path without / f.e  /home: " rsspath
read -rp "Please enter the JDownloader Folderwatch path without /  f.e /usr/bin/jd2 : " jdpath
read -rp "Please enter the Port for the RSSCrawler Webinterface: " rssport

# change Directory
mkdir $rsspath/
# Enter Directory
cd $rsspath/

# get RSScrawler
git clone https://github.com/rix1337/RSScrawler.git

# Enter RSScrawler Directory
cd RSScrawler

# Add RSScrawler Repo for pull option
git remote add rss https://github.com/rix1337/RSScrawler.git

#Create JDownloader Folder
mkdir $jdpath/folderwatch/

# Start RSSCrawler the first time (generation of Setting Files)
python RSScrawler.py

# Clear for a better overview
   clear

# Ausgeben des Hinweis der Pfade
echo "--------------------"
echo "RSScrawler Path is: $rsspath"
echo "JDownloader Folderwatch Path is: $jdpath"
echo "Your choosen Port is : $rssport"
echo "-------------"
echo ""
echo ""
echo " Please take a look at: https://github.com/rix1337/RSScrawler/
 If you like RSSCrawler, say thank you : https://github.com/rix1337/thanks"
echo ""

#Change Port
sed s/9090/$rssport/g -i $rsspath/RSScrawler/Einstellungen/RSScrawler.ini 

# Erneutes Starten von RSSCrawler
python RSScrawler.py --jd-pfad=$jdpath &
```



Leider ist kein .sh-File hier erlaubt und nen Fork wollt ich auch nicht erstellen, oder wie willst es machen? Ich arbeite aber noch weiter dran, aber man kann es verwenden.

LG

**Comment by rix1337** [comment]
Du kannst jederzeit einen Fork aufmachen, die Datei bspw. als setup.sh dazu packen, einen Pull Request aufmachen und deinen Fork dann direkt wieder löschen. Dann kann ich das mergen.

Ansonsten füg ich das Script einfach in einem der nächsten Commits ein.

Ich versuche gerade brauchbare Javascript-Hinweise einzubauen die sagen, wenn gespeichert wurde und fragen, wenn der Log geleert oder neugestarten werden soll. Das kann noch etwas dauern. Sobald ich erfolgreich bin pushe ich Version 2.0.10 mit deinem Setup script. Teste das aber auch kurz. Btw: Ich hatte das Script mal auf Englisch aufgesetzt, aber mir fiel auf, dass SJ nur aus Deutschland aufrufbar ist. Hab daher alles Rückübersetzt. Das würde ich mit dem Bash script auch machen. Der RSScrawler ergibt nur auf Deutsch Sinn.. Danke für die Arbeit. Das hilft sicher beim Einstieg!

> Warum erstellst du die Settings eig. nach Ausführen des Scripts und lässt die nicht schon im Rep auftauchen? Dann würde man sich das 2te mal starten sparen ;).

Als das ganze eine Konsolenanwendung war, musste ich irgendwie verhindern, dass das Programm einfach mal lossucht bzw. crawljobs in nicht vorhandenen Ordnern ablegt. Das brächte das Script nur zum Abstürzen. Daher fordert das Script mindestens den richtigen Pfad ein.

Ich kann aber mal das jd-pfad Parameter so überarbeiten, dass der Crawler direkt startet, wenn man den Pfad angibt.

**Comment by Itsie** [comment]
Hi,

ok, ja verstehe ich , werde dann weitere Dinge in Deutsch hinklatschen.
Danke dir erstmal, würde vorschlagen dass du es hier im REPO mit einbaust.

Freue mich schon auf die Änderungen, ah btw, kann es sein, dass das Webinterface immer einen neuen Prozess startet? : 
` 2089 root      20   0 1093908  21652   2252 S   1.3  1.1   0:01.71 /usr/bin/python RSScrawler.py --log-level DEBUG
  310 root      20   0  454480  65720   2732 S   0.3  3.4  21:53.97 python RSScrawler.py --log-level DEBUG
  493 root      20   0  459380  65728   3072 S   0.3  3.4  18:47.18 /usr/bin/python RSScrawler.py --log-level DEBUG
  858 root      20   0  458620  77044   7020 S   0.3  4.0  12:56.64 /usr/bin/python RSScrawler.py --log-level DEBUG
 1415 root      20   0  453792  43992   7148 S   0.3  2.3   5:17.22 /usr/bin/python RSScrawler.py --log-level DEBUG
    1 root      20   0   28156   1056    500 S   0.0  0.1   0:00.59 /sbin/init
   16 root      20   0   32960   1208    948 S   0.0  0.1   0:00.28 /lib/systemd/systemd-journald
   62 root      20   0   25392   7460    564 S   0.0  0.4   0:00.00 dhclient -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
   84 root      20   0   63308    588    120 S   0.0  0.0   0:00.00 /bin/login -f
   85 root      20   0   63308    592    120 S   0.0  0.0   0:00.01 /bin/login -f
   86 root      20   0   63308    584    120 S   0.0  0.0   0:00.00 /bin/login -f
   87 root      20   0   64908    592    120 S   0.0  0.0   0:00.00 /bin/login -f
   88 root      20   0   63308    584    120 S   0.0  0.0   0:00.00 /bin/login -f
   99 root      20   0   21828    448     48 S   0.0  0.0   0:00.00 -bash
  100 root      20   0   21828    444     48 S   0.0  0.0   0:00.00 -bash
  101 root      20   0   21828    428     48 S   0.0  0.0   0:00.00 -bash
  102 root      20   0   21828    456     48 S   0.0  0.0   0:00.00 -bash
  116 root      20   0   21828    456     40 S   0.0  0.0   0:00.00 -bash
  315 root      20   0  453956  48420   2740 S   0.0  2.5  22:20.62 /usr/bin/python RSScrawler.py --log-level DEBUG
  388 root      20   0  453844  70444   2860 S   0.0  3.6  20:26.51 /usr/bin/python RSScrawler.py --log-level DEBUG
`

Müsste mal schauen wie ich es verhinder.

LG

**Comment by rix1337** [comment]
> das Webinterface immer einen neuen Prozess startet? 

Das ist richtig. Nur so läuft der Webserver im Hintergrund, während das Script im Vordergrund seine Suchläufe durchführt.

Gedacht ist aber, dass bei Strg+C der gesamte Prozess endet. Wenn man während der Ausführung irgendetwas an den .py-Dateien ändert, startet cherrypy automatisch den Webserver neu. Vielleicht liegt es daran.

Dein Script muss ich noch testen, bevor ich es einfüge.

Grüße

**Comment by rix1337** [comment]
Der RSScrawler beendet sich jetzt außerdem nicht mehr, wenn man ihn das erste mal mit --jd-pfad startet.

**Comment by rix1337** [comment]
Dein Script ist jetzt getestet und eingefügt.

Folgende Ergänzungen:
1. Infos zum Spenden findet man im Webinterface, daher lass ich diese aus der Konsole weg.
2. Den folderwatch-Pfad automatisch zu erstellen ist eine Fehlerquelle. Wenn man im JDownloader die Ordnerüberwachung aktiviert, sollte der Pfad automatisch auftauchen. Nur von dort kann ein crawljob sinnvoll angenommen werden. Ich habe daher die entsprechende Option entfernt. (Zeit für eine Schritt-Für-Schritt-Anleitung mit Bildern im Wiki!)
3. Den RSScrawler-Pfad lasse ich komplett erstellen. Kann also ein beliebiger Pfad sein, den das Script dann automatisch anlegt (mkdir -p)

**Comment by Itsie** [comment]
Hi,

na das ist doch Perfekt. Etwas verwirrt nach Update:

`2016-10-04 17:48:49 - Marvels.Daredevil.S01.Complete.German.DTS-HD.DL.1080p.BluRay.AVC.REMUX-LeetHD - Release ignoriert (basierend auf ignore-Einstellung)
2016-10-04 17:48:49 - The.Returned.2012.S02.German.DL.1080p.BluRay.x264-RSG
2016-10-04 17:48:49 - I.Am.Soldier.2014.German.DL.1080p.BluRay.x264-ROOR
2016-10-04 17:48:49 - In.3.Tagen.bist.du.tot.2006.German.1080p.BluRay.x264-EXQUiSiTE
2016-10-04 17:48:49 - Person.of.Interest.S05.GERMAN.DUBBED.DL.1080p.BluRay.x264-TVP
2016-10-04 17:48:49 - The.Strain.S03.GERMAN.DUBBED.DL.1080p.WebHD.x264-TVP
2016-10-04 17:48:49 - Preacher.S01E01.German.AC3.BDRip.XViD-LeetXD - Release ignoriert (basierend auf ignore-Einstellung)
2016-10-04 17:48:49 - Chicago.Fire.S04.German.DL.1080p.BluRay.x264-RSG
2016-10-04 17:48:49 - Schlappschuss.3.Die.Junior.Liga.2008.German.1080p.HDTV.x264-TiPToP
2016-10-04 17:48:49 - Saw.I.Directors.Cut.2004.German.DL.DTS.1080p.BluRay.VC1-TiPToP
2016-10-04 17:48:49 - Saw.II.Directors.Cut.2005.German.DL.1080p.BluRay.VC1-TiPToP
2016-10-04 17:48:49 - Saw.III.Directors.Cut.2006.German.DL.DTS.1080p.BluRay.AVC-TiPToP
`

Webinterface Einstellungen:
MB-Filme:
PsO

SJ_Serien (ja ich weiss, Update hat mir gerade die "*" rausgenommen ;).:
Hawaii Five-0
Quantico
NCIS 
Blindspot 
Marvels Agents of S H I E L D
Legends of Tomorrow
Bones
NCIS Los Angeles
The Last Ship 
The Player 2015 
Lego Nexo Knights 

Ansonsten super Sache ;) Spende sollte unterwegs sein, bitte kurz bescheid geben.

LG

**Comment by rix1337** [comment]
Hm, irgendwo eine leere Zeile bzw. ein Leerzeichen drin?
Das Script sucht jetzt nach Umlauten und RegEx-Sonderzeichen in den nicht-regex Listen und entfernt diese.. das mit den * war also ein gewünschter Effekt.

Wenn du irgendwo eine Leerzeile drin hast, sag mal Bescheid, dann überarbeite ich die Entfernen-Funktion noch.

Ansonsten brauch ich mal deine RSScrawler.ini + deine .txt's (hochgeladen), dann schau ich mal drüber.

Alles zu seiner Zeit, so schnell wie möglich 👍 

Und vielen Dank. Ich sag Bescheid!

**Comment by Itsie** [comment]
Hey,

wie sind denn nu die richtigen Formate? Leider sind die ja nirgends mehr aufgeführt.
Hatte glaube ich das was eig. in die regex kommt in die normale geklatscht ;).

LG

**Comment by rix1337** [comment]
Achso, geh mal mit der Maus über eine der Zeilen im Webinterface.
![beispiel](https://cloud.githubusercontent.com/assets/9930448/19087438/40e022f0-8a72-11e6-9478-21babb6fd782.PNG)

**Comment by Itsie** [comment]
Ah ok sehe nun ;). Die Frage war wie Staffeln deklariert werden und /ob Trennzeichen von Nöten sind ;)

Hat sich nun erledigt !

**Comment by rix1337** [comment]
Sehr gut, dann wird es erst recht zeit für bilder im Wiki..

Viel Spaß erstmal mit dem RSScrawler!

**Comment by Itsie** [comment]
Danke , dein verarbeitungs Script läuft erstklassig ! Auch nochmal ein Lob hierfür !
TOP!

**Comment by rix1337** [comment]
Danke. Das Script ist natürlich auf meine Zwecke zugeschnitten.. wenn du da was ändern willst musst du forken. Wäre aber auch Mist, wenn es nicht ginge 👍 .. läuft bei mir 24/7.
