### ISSUE TITLE
Docker mit alpine oder kleinerem Basesystem aufsetzen.

### ISSUE THREAD

**Issue by Gutz-Pilz** [rix1337/RSScrawler#91]
Hi,

mir ist aufgefallen, dass der docker recht groß ist. ~700mb
Ich schätze man kann einiges an Platz einsparen wenn man ein schlankeres Basesystem verwenden würde.
wenn das allerdings zu viel aufwand ist, darfst du diesen Issue gerne ignorieren :)

Danke

**Comment by rix1337** [comment]
Gute Idee, schiebe ich aber seit ner Weile vor mir her, da die paketverwaltung auf alpine etwas anders aussieht.

Ich schließe den Request hier & öffne einen im docker-Repo

**Comment by rix1337** [comment]
Ist erledigt
