### ISSUE TITLE
Webinterface in Safari (macOS) - Dialogfenster ohne Funktion!

### ISSUE THREAD

**Issue by badrabbit** [rix1337/RSScrawler#96]
# [RSScrawler] Fehlermeldung

### Fehlerbeschreibung:

In der aktuellen Version des Browsers Safari (10.0.1) können die aufscheinenden Dialogfenster nicht benutzt werden. Sie poppen korrekt auf, jedoch bleiben sie unverändert und konstant stehen, egal welcher Button geklickt wird (OK/Abbrechen). 
Einzig ein Reload der Seite lässt die Dialogfenster wieder verschwinden, jedoch natürlich ohne jegliche Änderung der zuvor angeklickten Funktion.

Keine Probleme dieser Art in Firefox (49.0.2) 

### Informationen:

-macOS Sierra 10.12
-Safari (10.0.1)

-Version des RSScrawlers: v.2.2.2

### Logauszug:

Keine Fehlermeldung im Log.

**Comment by rix1337** [comment]
Danke erstmal für die ausführliche Fehlermeldung.

Kann das vorerst nicht testen, da nur auf Windows/Unix unterwegs.

Ich versuch mir die Tage mal macOS als VM aufzusetzen .. 
Kann also leider etwas dauern. Ich vermute, dass entweder JS oder mein Umlenken auf einen iFrame Probleme bereitet. Bis dahin kann ich leider nur Chrome oder Firefox für macOS empfehlen.

**Comment by badrabbit** [comment]
Ist kein dringendes Problem. Zum Glück müssen Einstellungen ja nur sehr selten vorgenommen werden (zumindest bei meinem Setup). Safari ist halt nur mein Hauptbrowser und da wäre es natürlich nett, wenn auch das RSSCrawler-Webinterface funkionieren würde.

Danke für die Info und Arbeit!

**Comment by rix1337** [comment]
Alles klar, wir werden sehen wie weit ich komme 👍 

Funktioniert das Speichern von Listen?

**Comment by rix1337** [comment]
Täte es im Ernstfall ein Workaround, der bei Safari einfach auf die Buttons verzichtet und stattdessen auf die Funktionsseiten umleitet (/speichern, etc.)?

**Comment by badrabbit** [comment]
Das Speichern von Listen funktioniert im Prinzip - nach dem Klick auf "Speichern" kommt das Hinweisfenster dass die Listen gespeichert wurden und ein Nestart benötigt wird ("OK", nicht klickbar).

Nach einem Reload der Seite sind die Listen-Änderungen sichtbar.

**Comment by badrabbit** [comment]
Der Workaround wäre sicher in Ordnung.

**Comment by rix1337** [comment]
Sehr gut, dann liegt es ausschließlich an den Buttons, nicht am iFrame, dem Speichern und JS generell.

Danke für die Infos

**Comment by rix1337** [comment]
Ab jetzt ist eine JavaScript-freie Unterseite auf /legacy verfügbar.

Die Hauptseite erkennt automatisch den User Agenten und leitet direkt auf /legacy um.

Getestet habe ich das auf Edge und IE, aber nicht mit Safari, mangels Mac.
Kurze Rückmeldung, ob es klappt erbeten.

**Comment by badrabbit** [comment]
Danke für den Fix!
Listen bearbeiten funktioniert soweit ich das beurteilen kann nun problemlos.

Allerdings kann ich über das Webinterface nicht mehr Neustarten. Nach dem Klick auf den Neustarten-button wird versucht folgende Seite zu öffnen:
http://10.0.1.10:9090/neustart?wert=1

Und hier kommt immer die Browser-Meldung, dass die Seite nicht geöffnet werden kann.

**Comment by rix1337** [comment]
Dann scheint das Problem behoben zu sein.

Der Neustart war mein Grund Javascript einzusetzen. RSScrawler startet neu, und in dem Moment kann die Seite natürlich nicht laden. Was du siehst ist also ein erfolgreicher Neustart

**Comment by badrabbit** [comment]
;-) Alles klar. Danke nochmal!

**Comment by rix1337** [comment]
Kein Thema. Danke für die Fehlermeldung.
